// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dzhyun.advert.proto

package com.dzhyun.proto;

public final class DzhyunAdvert {
  private DzhyunAdvert() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ADPutResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dzhyun.ADPutResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string ErrCode = 1;</code>
     *
     * <pre>
     * 返回结果码，当为0时，请求被正常处理
     * </pre>
     */
    boolean hasErrCode();
    /**
     * <code>required string ErrCode = 1;</code>
     *
     * <pre>
     * 返回结果码，当为0时，请求被正常处理
     * </pre>
     */
    java.lang.String getErrCode();
    /**
     * <code>required string ErrCode = 1;</code>
     *
     * <pre>
     * 返回结果码，当为0时，请求被正常处理
     * </pre>
     */
    com.google.protobuf.ByteString
        getErrCodeBytes();
  }
  /**
   * Protobuf type {@code dzhyun.ADPutResponse}
   *
   * <pre>
   * 通用的广告响应消息
   * </pre>
   */
  public static final class ADPutResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:dzhyun.ADPutResponse)
      ADPutResponseOrBuilder {
    // Use ADPutResponse.newBuilder() to construct.
    private ADPutResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ADPutResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ADPutResponse defaultInstance;
    public static ADPutResponse getDefaultInstance() {
      return defaultInstance;
    }

    public ADPutResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ADPutResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              errCode_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dzhyun.proto.DzhyunAdvert.internal_static_dzhyun_ADPutResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dzhyun.proto.DzhyunAdvert.internal_static_dzhyun_ADPutResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dzhyun.proto.DzhyunAdvert.ADPutResponse.class, com.dzhyun.proto.DzhyunAdvert.ADPutResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<ADPutResponse> PARSER =
        new com.google.protobuf.AbstractParser<ADPutResponse>() {
      public ADPutResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ADPutResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ADPutResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ERRCODE_FIELD_NUMBER = 1;
    private java.lang.Object errCode_;
    /**
     * <code>required string ErrCode = 1;</code>
     *
     * <pre>
     * 返回结果码，当为0时，请求被正常处理
     * </pre>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string ErrCode = 1;</code>
     *
     * <pre>
     * 返回结果码，当为0时，请求被正常处理
     * </pre>
     */
    public java.lang.String getErrCode() {
      java.lang.Object ref = errCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ErrCode = 1;</code>
     *
     * <pre>
     * 返回结果码，当为0时，请求被正常处理
     * </pre>
     */
    public com.google.protobuf.ByteString
        getErrCodeBytes() {
      java.lang.Object ref = errCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      errCode_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasErrCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getErrCodeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getErrCodeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.dzhyun.proto.DzhyunAdvert.ADPutResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADPutResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADPutResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADPutResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADPutResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADPutResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADPutResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADPutResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADPutResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADPutResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dzhyun.proto.DzhyunAdvert.ADPutResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dzhyun.ADPutResponse}
     *
     * <pre>
     * 通用的广告响应消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dzhyun.ADPutResponse)
        com.dzhyun.proto.DzhyunAdvert.ADPutResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dzhyun.proto.DzhyunAdvert.internal_static_dzhyun_ADPutResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dzhyun.proto.DzhyunAdvert.internal_static_dzhyun_ADPutResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dzhyun.proto.DzhyunAdvert.ADPutResponse.class, com.dzhyun.proto.DzhyunAdvert.ADPutResponse.Builder.class);
      }

      // Construct using com.dzhyun.proto.DzhyunAdvert.ADPutResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        errCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dzhyun.proto.DzhyunAdvert.internal_static_dzhyun_ADPutResponse_descriptor;
      }

      public com.dzhyun.proto.DzhyunAdvert.ADPutResponse getDefaultInstanceForType() {
        return com.dzhyun.proto.DzhyunAdvert.ADPutResponse.getDefaultInstance();
      }

      public com.dzhyun.proto.DzhyunAdvert.ADPutResponse build() {
        com.dzhyun.proto.DzhyunAdvert.ADPutResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dzhyun.proto.DzhyunAdvert.ADPutResponse buildPartial() {
        com.dzhyun.proto.DzhyunAdvert.ADPutResponse result = new com.dzhyun.proto.DzhyunAdvert.ADPutResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errCode_ = errCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dzhyun.proto.DzhyunAdvert.ADPutResponse) {
          return mergeFrom((com.dzhyun.proto.DzhyunAdvert.ADPutResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dzhyun.proto.DzhyunAdvert.ADPutResponse other) {
        if (other == com.dzhyun.proto.DzhyunAdvert.ADPutResponse.getDefaultInstance()) return this;
        if (other.hasErrCode()) {
          bitField0_ |= 0x00000001;
          errCode_ = other.errCode_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasErrCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dzhyun.proto.DzhyunAdvert.ADPutResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dzhyun.proto.DzhyunAdvert.ADPutResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object errCode_ = "";
      /**
       * <code>required string ErrCode = 1;</code>
       *
       * <pre>
       * 返回结果码，当为0时，请求被正常处理
       * </pre>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string ErrCode = 1;</code>
       *
       * <pre>
       * 返回结果码，当为0时，请求被正常处理
       * </pre>
       */
      public java.lang.String getErrCode() {
        java.lang.Object ref = errCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ErrCode = 1;</code>
       *
       * <pre>
       * 返回结果码，当为0时，请求被正常处理
       * </pre>
       */
      public com.google.protobuf.ByteString
          getErrCodeBytes() {
        java.lang.Object ref = errCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ErrCode = 1;</code>
       *
       * <pre>
       * 返回结果码，当为0时，请求被正常处理
       * </pre>
       */
      public Builder setErrCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ErrCode = 1;</code>
       *
       * <pre>
       * 返回结果码，当为0时，请求被正常处理
       * </pre>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errCode_ = getDefaultInstance().getErrCode();
        onChanged();
        return this;
      }
      /**
       * <code>required string ErrCode = 1;</code>
       *
       * <pre>
       * 返回结果码，当为0时，请求被正常处理
       * </pre>
       */
      public Builder setErrCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        errCode_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dzhyun.ADPutResponse)
    }

    static {
      defaultInstance = new ADPutResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:dzhyun.ADPutResponse)
  }

  public interface ADInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dzhyun.ADInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string Slot = 1;</code>
     */
    boolean hasSlot();
    /**
     * <code>required string Slot = 1;</code>
     */
    java.lang.String getSlot();
    /**
     * <code>required string Slot = 1;</code>
     */
    com.google.protobuf.ByteString
        getSlotBytes();

    /**
     * <code>required string Data = 2;</code>
     */
    boolean hasData();
    /**
     * <code>required string Data = 2;</code>
     */
    java.lang.String getData();
    /**
     * <code>required string Data = 2;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>required string Version = 3;</code>
     */
    boolean hasVersion();
    /**
     * <code>required string Version = 3;</code>
     */
    java.lang.String getVersion();
    /**
     * <code>required string Version = 3;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();
  }
  /**
   * Protobuf type {@code dzhyun.ADInfo}
   */
  public static final class ADInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:dzhyun.ADInfo)
      ADInfoOrBuilder {
    // Use ADInfo.newBuilder() to construct.
    private ADInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ADInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ADInfo defaultInstance;
    public static ADInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ADInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ADInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              slot_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              data_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              version_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dzhyun.proto.DzhyunAdvert.internal_static_dzhyun_ADInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dzhyun.proto.DzhyunAdvert.internal_static_dzhyun_ADInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dzhyun.proto.DzhyunAdvert.ADInfo.class, com.dzhyun.proto.DzhyunAdvert.ADInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ADInfo> PARSER =
        new com.google.protobuf.AbstractParser<ADInfo>() {
      public ADInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ADInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ADInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SLOT_FIELD_NUMBER = 1;
    private java.lang.Object slot_;
    /**
     * <code>required string Slot = 1;</code>
     */
    public boolean hasSlot() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string Slot = 1;</code>
     */
    public java.lang.String getSlot() {
      java.lang.Object ref = slot_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          slot_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Slot = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSlotBytes() {
      java.lang.Object ref = slot_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        slot_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private java.lang.Object data_;
    /**
     * <code>required string Data = 2;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string Data = 2;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Data = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 3;
    private java.lang.Object version_;
    /**
     * <code>required string Version = 3;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string Version = 3;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Version = 3;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      slot_ = "";
      data_ = "";
      version_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSlot()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSlotBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDataBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getVersionBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSlotBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDataBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getVersionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.dzhyun.proto.DzhyunAdvert.ADInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dzhyun.proto.DzhyunAdvert.ADInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dzhyun.ADInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dzhyun.ADInfo)
        com.dzhyun.proto.DzhyunAdvert.ADInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dzhyun.proto.DzhyunAdvert.internal_static_dzhyun_ADInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dzhyun.proto.DzhyunAdvert.internal_static_dzhyun_ADInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dzhyun.proto.DzhyunAdvert.ADInfo.class, com.dzhyun.proto.DzhyunAdvert.ADInfo.Builder.class);
      }

      // Construct using com.dzhyun.proto.DzhyunAdvert.ADInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        slot_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dzhyun.proto.DzhyunAdvert.internal_static_dzhyun_ADInfo_descriptor;
      }

      public com.dzhyun.proto.DzhyunAdvert.ADInfo getDefaultInstanceForType() {
        return com.dzhyun.proto.DzhyunAdvert.ADInfo.getDefaultInstance();
      }

      public com.dzhyun.proto.DzhyunAdvert.ADInfo build() {
        com.dzhyun.proto.DzhyunAdvert.ADInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dzhyun.proto.DzhyunAdvert.ADInfo buildPartial() {
        com.dzhyun.proto.DzhyunAdvert.ADInfo result = new com.dzhyun.proto.DzhyunAdvert.ADInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.slot_ = slot_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.version_ = version_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dzhyun.proto.DzhyunAdvert.ADInfo) {
          return mergeFrom((com.dzhyun.proto.DzhyunAdvert.ADInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dzhyun.proto.DzhyunAdvert.ADInfo other) {
        if (other == com.dzhyun.proto.DzhyunAdvert.ADInfo.getDefaultInstance()) return this;
        if (other.hasSlot()) {
          bitField0_ |= 0x00000001;
          slot_ = other.slot_;
          onChanged();
        }
        if (other.hasData()) {
          bitField0_ |= 0x00000002;
          data_ = other.data_;
          onChanged();
        }
        if (other.hasVersion()) {
          bitField0_ |= 0x00000004;
          version_ = other.version_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSlot()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        if (!hasVersion()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dzhyun.proto.DzhyunAdvert.ADInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dzhyun.proto.DzhyunAdvert.ADInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object slot_ = "";
      /**
       * <code>required string Slot = 1;</code>
       */
      public boolean hasSlot() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string Slot = 1;</code>
       */
      public java.lang.String getSlot() {
        java.lang.Object ref = slot_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            slot_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string Slot = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSlotBytes() {
        java.lang.Object ref = slot_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          slot_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Slot = 1;</code>
       */
      public Builder setSlot(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        slot_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Slot = 1;</code>
       */
      public Builder clearSlot() {
        bitField0_ = (bitField0_ & ~0x00000001);
        slot_ = getDefaultInstance().getSlot();
        onChanged();
        return this;
      }
      /**
       * <code>required string Slot = 1;</code>
       */
      public Builder setSlotBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        slot_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>required string Data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string Data = 2;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            data_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string Data = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Data = 2;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>required string Data = 2;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>required string Version = 3;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string Version = 3;</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            version_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string Version = 3;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Version = 3;</code>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Version = 3;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>required string Version = 3;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dzhyun.ADInfo)
    }

    static {
      defaultInstance = new ADInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:dzhyun.ADInfo)
  }

  public interface ADGetResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dzhyun.ADGetResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
     */
    java.util.List<com.dzhyun.proto.DzhyunAdvert.ADInfo> 
        getSlotsList();
    /**
     * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
     */
    com.dzhyun.proto.DzhyunAdvert.ADInfo getSlots(int index);
    /**
     * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
     */
    int getSlotsCount();
    /**
     * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
     */
    java.util.List<? extends com.dzhyun.proto.DzhyunAdvert.ADInfoOrBuilder> 
        getSlotsOrBuilderList();
    /**
     * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
     */
    com.dzhyun.proto.DzhyunAdvert.ADInfoOrBuilder getSlotsOrBuilder(
        int index);

    /**
     * <code>required string PropVersion = 2;</code>
     */
    boolean hasPropVersion();
    /**
     * <code>required string PropVersion = 2;</code>
     */
    java.lang.String getPropVersion();
    /**
     * <code>required string PropVersion = 2;</code>
     */
    com.google.protobuf.ByteString
        getPropVersionBytes();
  }
  /**
   * Protobuf type {@code dzhyun.ADGetResponse}
   */
  public static final class ADGetResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:dzhyun.ADGetResponse)
      ADGetResponseOrBuilder {
    // Use ADGetResponse.newBuilder() to construct.
    private ADGetResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ADGetResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ADGetResponse defaultInstance;
    public static ADGetResponse getDefaultInstance() {
      return defaultInstance;
    }

    public ADGetResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ADGetResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                slots_ = new java.util.ArrayList<com.dzhyun.proto.DzhyunAdvert.ADInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              slots_.add(input.readMessage(com.dzhyun.proto.DzhyunAdvert.ADInfo.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              propVersion_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          slots_ = java.util.Collections.unmodifiableList(slots_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dzhyun.proto.DzhyunAdvert.internal_static_dzhyun_ADGetResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dzhyun.proto.DzhyunAdvert.internal_static_dzhyun_ADGetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dzhyun.proto.DzhyunAdvert.ADGetResponse.class, com.dzhyun.proto.DzhyunAdvert.ADGetResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<ADGetResponse> PARSER =
        new com.google.protobuf.AbstractParser<ADGetResponse>() {
      public ADGetResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ADGetResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ADGetResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SLOTS_FIELD_NUMBER = 1;
    private java.util.List<com.dzhyun.proto.DzhyunAdvert.ADInfo> slots_;
    /**
     * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
     */
    public java.util.List<com.dzhyun.proto.DzhyunAdvert.ADInfo> getSlotsList() {
      return slots_;
    }
    /**
     * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
     */
    public java.util.List<? extends com.dzhyun.proto.DzhyunAdvert.ADInfoOrBuilder> 
        getSlotsOrBuilderList() {
      return slots_;
    }
    /**
     * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
     */
    public int getSlotsCount() {
      return slots_.size();
    }
    /**
     * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
     */
    public com.dzhyun.proto.DzhyunAdvert.ADInfo getSlots(int index) {
      return slots_.get(index);
    }
    /**
     * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
     */
    public com.dzhyun.proto.DzhyunAdvert.ADInfoOrBuilder getSlotsOrBuilder(
        int index) {
      return slots_.get(index);
    }

    public static final int PROPVERSION_FIELD_NUMBER = 2;
    private java.lang.Object propVersion_;
    /**
     * <code>required string PropVersion = 2;</code>
     */
    public boolean hasPropVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string PropVersion = 2;</code>
     */
    public java.lang.String getPropVersion() {
      java.lang.Object ref = propVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          propVersion_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string PropVersion = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPropVersionBytes() {
      java.lang.Object ref = propVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        propVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      slots_ = java.util.Collections.emptyList();
      propVersion_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPropVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getSlotsCount(); i++) {
        if (!getSlots(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < slots_.size(); i++) {
        output.writeMessage(1, slots_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getPropVersionBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < slots_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, slots_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPropVersionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.dzhyun.proto.DzhyunAdvert.ADGetResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADGetResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADGetResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADGetResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADGetResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADGetResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADGetResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADGetResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADGetResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dzhyun.proto.DzhyunAdvert.ADGetResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dzhyun.proto.DzhyunAdvert.ADGetResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dzhyun.ADGetResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dzhyun.ADGetResponse)
        com.dzhyun.proto.DzhyunAdvert.ADGetResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dzhyun.proto.DzhyunAdvert.internal_static_dzhyun_ADGetResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dzhyun.proto.DzhyunAdvert.internal_static_dzhyun_ADGetResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dzhyun.proto.DzhyunAdvert.ADGetResponse.class, com.dzhyun.proto.DzhyunAdvert.ADGetResponse.Builder.class);
      }

      // Construct using com.dzhyun.proto.DzhyunAdvert.ADGetResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSlotsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (slotsBuilder_ == null) {
          slots_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          slotsBuilder_.clear();
        }
        propVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dzhyun.proto.DzhyunAdvert.internal_static_dzhyun_ADGetResponse_descriptor;
      }

      public com.dzhyun.proto.DzhyunAdvert.ADGetResponse getDefaultInstanceForType() {
        return com.dzhyun.proto.DzhyunAdvert.ADGetResponse.getDefaultInstance();
      }

      public com.dzhyun.proto.DzhyunAdvert.ADGetResponse build() {
        com.dzhyun.proto.DzhyunAdvert.ADGetResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dzhyun.proto.DzhyunAdvert.ADGetResponse buildPartial() {
        com.dzhyun.proto.DzhyunAdvert.ADGetResponse result = new com.dzhyun.proto.DzhyunAdvert.ADGetResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (slotsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            slots_ = java.util.Collections.unmodifiableList(slots_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.slots_ = slots_;
        } else {
          result.slots_ = slotsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.propVersion_ = propVersion_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dzhyun.proto.DzhyunAdvert.ADGetResponse) {
          return mergeFrom((com.dzhyun.proto.DzhyunAdvert.ADGetResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dzhyun.proto.DzhyunAdvert.ADGetResponse other) {
        if (other == com.dzhyun.proto.DzhyunAdvert.ADGetResponse.getDefaultInstance()) return this;
        if (slotsBuilder_ == null) {
          if (!other.slots_.isEmpty()) {
            if (slots_.isEmpty()) {
              slots_ = other.slots_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSlotsIsMutable();
              slots_.addAll(other.slots_);
            }
            onChanged();
          }
        } else {
          if (!other.slots_.isEmpty()) {
            if (slotsBuilder_.isEmpty()) {
              slotsBuilder_.dispose();
              slotsBuilder_ = null;
              slots_ = other.slots_;
              bitField0_ = (bitField0_ & ~0x00000001);
              slotsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSlotsFieldBuilder() : null;
            } else {
              slotsBuilder_.addAllMessages(other.slots_);
            }
          }
        }
        if (other.hasPropVersion()) {
          bitField0_ |= 0x00000002;
          propVersion_ = other.propVersion_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPropVersion()) {
          
          return false;
        }
        for (int i = 0; i < getSlotsCount(); i++) {
          if (!getSlots(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dzhyun.proto.DzhyunAdvert.ADGetResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dzhyun.proto.DzhyunAdvert.ADGetResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.dzhyun.proto.DzhyunAdvert.ADInfo> slots_ =
        java.util.Collections.emptyList();
      private void ensureSlotsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          slots_ = new java.util.ArrayList<com.dzhyun.proto.DzhyunAdvert.ADInfo>(slots_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.dzhyun.proto.DzhyunAdvert.ADInfo, com.dzhyun.proto.DzhyunAdvert.ADInfo.Builder, com.dzhyun.proto.DzhyunAdvert.ADInfoOrBuilder> slotsBuilder_;

      /**
       * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
       */
      public java.util.List<com.dzhyun.proto.DzhyunAdvert.ADInfo> getSlotsList() {
        if (slotsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(slots_);
        } else {
          return slotsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
       */
      public int getSlotsCount() {
        if (slotsBuilder_ == null) {
          return slots_.size();
        } else {
          return slotsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
       */
      public com.dzhyun.proto.DzhyunAdvert.ADInfo getSlots(int index) {
        if (slotsBuilder_ == null) {
          return slots_.get(index);
        } else {
          return slotsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
       */
      public Builder setSlots(
          int index, com.dzhyun.proto.DzhyunAdvert.ADInfo value) {
        if (slotsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSlotsIsMutable();
          slots_.set(index, value);
          onChanged();
        } else {
          slotsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
       */
      public Builder setSlots(
          int index, com.dzhyun.proto.DzhyunAdvert.ADInfo.Builder builderForValue) {
        if (slotsBuilder_ == null) {
          ensureSlotsIsMutable();
          slots_.set(index, builderForValue.build());
          onChanged();
        } else {
          slotsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
       */
      public Builder addSlots(com.dzhyun.proto.DzhyunAdvert.ADInfo value) {
        if (slotsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSlotsIsMutable();
          slots_.add(value);
          onChanged();
        } else {
          slotsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
       */
      public Builder addSlots(
          int index, com.dzhyun.proto.DzhyunAdvert.ADInfo value) {
        if (slotsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSlotsIsMutable();
          slots_.add(index, value);
          onChanged();
        } else {
          slotsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
       */
      public Builder addSlots(
          com.dzhyun.proto.DzhyunAdvert.ADInfo.Builder builderForValue) {
        if (slotsBuilder_ == null) {
          ensureSlotsIsMutable();
          slots_.add(builderForValue.build());
          onChanged();
        } else {
          slotsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
       */
      public Builder addSlots(
          int index, com.dzhyun.proto.DzhyunAdvert.ADInfo.Builder builderForValue) {
        if (slotsBuilder_ == null) {
          ensureSlotsIsMutable();
          slots_.add(index, builderForValue.build());
          onChanged();
        } else {
          slotsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
       */
      public Builder addAllSlots(
          java.lang.Iterable<? extends com.dzhyun.proto.DzhyunAdvert.ADInfo> values) {
        if (slotsBuilder_ == null) {
          ensureSlotsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, slots_);
          onChanged();
        } else {
          slotsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
       */
      public Builder clearSlots() {
        if (slotsBuilder_ == null) {
          slots_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          slotsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
       */
      public Builder removeSlots(int index) {
        if (slotsBuilder_ == null) {
          ensureSlotsIsMutable();
          slots_.remove(index);
          onChanged();
        } else {
          slotsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
       */
      public com.dzhyun.proto.DzhyunAdvert.ADInfo.Builder getSlotsBuilder(
          int index) {
        return getSlotsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
       */
      public com.dzhyun.proto.DzhyunAdvert.ADInfoOrBuilder getSlotsOrBuilder(
          int index) {
        if (slotsBuilder_ == null) {
          return slots_.get(index);  } else {
          return slotsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
       */
      public java.util.List<? extends com.dzhyun.proto.DzhyunAdvert.ADInfoOrBuilder> 
           getSlotsOrBuilderList() {
        if (slotsBuilder_ != null) {
          return slotsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(slots_);
        }
      }
      /**
       * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
       */
      public com.dzhyun.proto.DzhyunAdvert.ADInfo.Builder addSlotsBuilder() {
        return getSlotsFieldBuilder().addBuilder(
            com.dzhyun.proto.DzhyunAdvert.ADInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
       */
      public com.dzhyun.proto.DzhyunAdvert.ADInfo.Builder addSlotsBuilder(
          int index) {
        return getSlotsFieldBuilder().addBuilder(
            index, com.dzhyun.proto.DzhyunAdvert.ADInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .dzhyun.ADInfo Slots = 1;</code>
       */
      public java.util.List<com.dzhyun.proto.DzhyunAdvert.ADInfo.Builder> 
           getSlotsBuilderList() {
        return getSlotsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.dzhyun.proto.DzhyunAdvert.ADInfo, com.dzhyun.proto.DzhyunAdvert.ADInfo.Builder, com.dzhyun.proto.DzhyunAdvert.ADInfoOrBuilder> 
          getSlotsFieldBuilder() {
        if (slotsBuilder_ == null) {
          slotsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.dzhyun.proto.DzhyunAdvert.ADInfo, com.dzhyun.proto.DzhyunAdvert.ADInfo.Builder, com.dzhyun.proto.DzhyunAdvert.ADInfoOrBuilder>(
                  slots_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          slots_ = null;
        }
        return slotsBuilder_;
      }

      private java.lang.Object propVersion_ = "";
      /**
       * <code>required string PropVersion = 2;</code>
       */
      public boolean hasPropVersion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string PropVersion = 2;</code>
       */
      public java.lang.String getPropVersion() {
        java.lang.Object ref = propVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            propVersion_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string PropVersion = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPropVersionBytes() {
        java.lang.Object ref = propVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          propVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string PropVersion = 2;</code>
       */
      public Builder setPropVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        propVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string PropVersion = 2;</code>
       */
      public Builder clearPropVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        propVersion_ = getDefaultInstance().getPropVersion();
        onChanged();
        return this;
      }
      /**
       * <code>required string PropVersion = 2;</code>
       */
      public Builder setPropVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        propVersion_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dzhyun.ADGetResponse)
    }

    static {
      defaultInstance = new ADGetResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:dzhyun.ADGetResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dzhyun_ADPutResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dzhyun_ADPutResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dzhyun_ADInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dzhyun_ADInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dzhyun_ADGetResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dzhyun_ADGetResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023dzhyun.advert.proto\022\006dzhyun\" \n\rADPutRe" +
      "sponse\022\017\n\007ErrCode\030\001 \002(\t\"5\n\006ADInfo\022\014\n\004Slo" +
      "t\030\001 \002(\t\022\014\n\004Data\030\002 \002(\t\022\017\n\007Version\030\003 \002(\t\"C" +
      "\n\rADGetResponse\022\035\n\005Slots\030\001 \003(\0132\016.dzhyun." +
      "ADInfo\022\023\n\013PropVersion\030\002 \002(\tB\022\n\020com.dzhyu" +
      "n.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_dzhyun_ADPutResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dzhyun_ADPutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_dzhyun_ADPutResponse_descriptor,
        new java.lang.String[] { "ErrCode", });
    internal_static_dzhyun_ADInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dzhyun_ADInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_dzhyun_ADInfo_descriptor,
        new java.lang.String[] { "Slot", "Data", "Version", });
    internal_static_dzhyun_ADGetResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dzhyun_ADGetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_dzhyun_ADGetResponse_descriptor,
        new java.lang.String[] { "Slots", "PropVersion", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
