// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dzhyun.marketstatus.proto

package com.dzhyun.proto;

public final class DzhyunMarketstatus {
  private DzhyunMarketstatus() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MarketStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dzhyun.MarketStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 Market = 1;</code>
     */
    boolean hasMarket();
    /**
     * <code>required int64 Market = 1;</code>
     */
    long getMarket();

    /**
     * <code>optional int64 Static_day = 2;</code>
     *
     * <pre>
     * static_day
     * </pre>
     */
    boolean hasStaticDay();
    /**
     * <code>optional int64 Static_day = 2;</code>
     *
     * <pre>
     * static_day
     * </pre>
     */
    long getStaticDay();

    /**
     * <code>optional int64 Closestatus = 3;</code>
     *
     * <pre>
     * closestatus
     * </pre>
     */
    boolean hasClosestatus();
    /**
     * <code>optional int64 Closestatus = 3;</code>
     *
     * <pre>
     * closestatus
     * </pre>
     */
    long getClosestatus();

    /**
     * <code>optional int64 Ip = 4;</code>
     *
     * <pre>
     * ip
     * </pre>
     */
    boolean hasIp();
    /**
     * <code>optional int64 Ip = 4;</code>
     *
     * <pre>
     * ip
     * </pre>
     */
    long getIp();

    /**
     * <code>optional int64 Init_time = 5;</code>
     *
     * <pre>
     * init_time
     * </pre>
     */
    boolean hasInitTime();
    /**
     * <code>optional int64 Init_time = 5;</code>
     *
     * <pre>
     * init_time
     * </pre>
     */
    long getInitTime();

    /**
     * <code>optional int64 Static_ver = 6;</code>
     *
     * <pre>
     * static_ver
     * </pre>
     */
    boolean hasStaticVer();
    /**
     * <code>optional int64 Static_ver = 6;</code>
     *
     * <pre>
     * static_ver
     * </pre>
     */
    long getStaticVer();

    /**
     * <code>optional int64 Timezonebias = 7;</code>
     *
     * <pre>
     * timezonebias
     * </pre>
     */
    boolean hasTimezonebias();
    /**
     * <code>optional int64 Timezonebias = 7;</code>
     *
     * <pre>
     * timezonebias
     * </pre>
     */
    long getTimezonebias();

    /**
     * <code>optional int64 Markettype = 8;</code>
     *
     * <pre>
     * markettype
     * </pre>
     */
    boolean hasMarkettype();
    /**
     * <code>optional int64 Markettype = 8;</code>
     *
     * <pre>
     * markettype
     * </pre>
     */
    long getMarkettype();

    /**
     * <code>optional int64 Marketattr = 9;</code>
     *
     * <pre>
     * marketattr
     * </pre>
     */
    boolean hasMarketattr();
    /**
     * <code>optional int64 Marketattr = 9;</code>
     *
     * <pre>
     * marketattr
     * </pre>
     */
    long getMarketattr();

    /**
     * <code>optional int64 Numopentime = 10;</code>
     *
     * <pre>
     * numopentime
     * </pre>
     */
    boolean hasNumopentime();
    /**
     * <code>optional int64 Numopentime = 10;</code>
     *
     * <pre>
     * numopentime
     * </pre>
     */
    long getNumopentime();

    /**
     * <code>optional int64 Change_num = 11;</code>
     *
     * <pre>
     * change_num
     * </pre>
     */
    boolean hasChangeNum();
    /**
     * <code>optional int64 Change_num = 11;</code>
     *
     * <pre>
     * change_num
     * </pre>
     */
    long getChangeNum();
  }
  /**
   * Protobuf type {@code dzhyun.MarketStatus}
   */
  public static final class MarketStatus extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:dzhyun.MarketStatus)
      MarketStatusOrBuilder {
    // Use MarketStatus.newBuilder() to construct.
    private MarketStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MarketStatus(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MarketStatus defaultInstance;
    public static MarketStatus getDefaultInstance() {
      return defaultInstance;
    }

    public MarketStatus getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MarketStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              market_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              staticDay_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              closestatus_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              ip_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              initTime_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              staticVer_ = input.readInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              timezonebias_ = input.readInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              markettype_ = input.readInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              marketattr_ = input.readInt64();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              numopentime_ = input.readInt64();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              changeNum_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dzhyun.proto.DzhyunMarketstatus.internal_static_dzhyun_MarketStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dzhyun.proto.DzhyunMarketstatus.internal_static_dzhyun_MarketStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dzhyun.proto.DzhyunMarketstatus.MarketStatus.class, com.dzhyun.proto.DzhyunMarketstatus.MarketStatus.Builder.class);
    }

    public static com.google.protobuf.Parser<MarketStatus> PARSER =
        new com.google.protobuf.AbstractParser<MarketStatus>() {
      public MarketStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MarketStatus(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MarketStatus> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MARKET_FIELD_NUMBER = 1;
    private long market_;
    /**
     * <code>required int64 Market = 1;</code>
     */
    public boolean hasMarket() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 Market = 1;</code>
     */
    public long getMarket() {
      return market_;
    }

    public static final int STATIC_DAY_FIELD_NUMBER = 2;
    private long staticDay_;
    /**
     * <code>optional int64 Static_day = 2;</code>
     *
     * <pre>
     * static_day
     * </pre>
     */
    public boolean hasStaticDay() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 Static_day = 2;</code>
     *
     * <pre>
     * static_day
     * </pre>
     */
    public long getStaticDay() {
      return staticDay_;
    }

    public static final int CLOSESTATUS_FIELD_NUMBER = 3;
    private long closestatus_;
    /**
     * <code>optional int64 Closestatus = 3;</code>
     *
     * <pre>
     * closestatus
     * </pre>
     */
    public boolean hasClosestatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 Closestatus = 3;</code>
     *
     * <pre>
     * closestatus
     * </pre>
     */
    public long getClosestatus() {
      return closestatus_;
    }

    public static final int IP_FIELD_NUMBER = 4;
    private long ip_;
    /**
     * <code>optional int64 Ip = 4;</code>
     *
     * <pre>
     * ip
     * </pre>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 Ip = 4;</code>
     *
     * <pre>
     * ip
     * </pre>
     */
    public long getIp() {
      return ip_;
    }

    public static final int INIT_TIME_FIELD_NUMBER = 5;
    private long initTime_;
    /**
     * <code>optional int64 Init_time = 5;</code>
     *
     * <pre>
     * init_time
     * </pre>
     */
    public boolean hasInitTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 Init_time = 5;</code>
     *
     * <pre>
     * init_time
     * </pre>
     */
    public long getInitTime() {
      return initTime_;
    }

    public static final int STATIC_VER_FIELD_NUMBER = 6;
    private long staticVer_;
    /**
     * <code>optional int64 Static_ver = 6;</code>
     *
     * <pre>
     * static_ver
     * </pre>
     */
    public boolean hasStaticVer() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 Static_ver = 6;</code>
     *
     * <pre>
     * static_ver
     * </pre>
     */
    public long getStaticVer() {
      return staticVer_;
    }

    public static final int TIMEZONEBIAS_FIELD_NUMBER = 7;
    private long timezonebias_;
    /**
     * <code>optional int64 Timezonebias = 7;</code>
     *
     * <pre>
     * timezonebias
     * </pre>
     */
    public boolean hasTimezonebias() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int64 Timezonebias = 7;</code>
     *
     * <pre>
     * timezonebias
     * </pre>
     */
    public long getTimezonebias() {
      return timezonebias_;
    }

    public static final int MARKETTYPE_FIELD_NUMBER = 8;
    private long markettype_;
    /**
     * <code>optional int64 Markettype = 8;</code>
     *
     * <pre>
     * markettype
     * </pre>
     */
    public boolean hasMarkettype() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int64 Markettype = 8;</code>
     *
     * <pre>
     * markettype
     * </pre>
     */
    public long getMarkettype() {
      return markettype_;
    }

    public static final int MARKETATTR_FIELD_NUMBER = 9;
    private long marketattr_;
    /**
     * <code>optional int64 Marketattr = 9;</code>
     *
     * <pre>
     * marketattr
     * </pre>
     */
    public boolean hasMarketattr() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int64 Marketattr = 9;</code>
     *
     * <pre>
     * marketattr
     * </pre>
     */
    public long getMarketattr() {
      return marketattr_;
    }

    public static final int NUMOPENTIME_FIELD_NUMBER = 10;
    private long numopentime_;
    /**
     * <code>optional int64 Numopentime = 10;</code>
     *
     * <pre>
     * numopentime
     * </pre>
     */
    public boolean hasNumopentime() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int64 Numopentime = 10;</code>
     *
     * <pre>
     * numopentime
     * </pre>
     */
    public long getNumopentime() {
      return numopentime_;
    }

    public static final int CHANGE_NUM_FIELD_NUMBER = 11;
    private long changeNum_;
    /**
     * <code>optional int64 Change_num = 11;</code>
     *
     * <pre>
     * change_num
     * </pre>
     */
    public boolean hasChangeNum() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int64 Change_num = 11;</code>
     *
     * <pre>
     * change_num
     * </pre>
     */
    public long getChangeNum() {
      return changeNum_;
    }

    private void initFields() {
      market_ = 0L;
      staticDay_ = 0L;
      closestatus_ = 0L;
      ip_ = 0L;
      initTime_ = 0L;
      staticVer_ = 0L;
      timezonebias_ = 0L;
      markettype_ = 0L;
      marketattr_ = 0L;
      numopentime_ = 0L;
      changeNum_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMarket()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, market_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, staticDay_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, closestatus_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, ip_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, initTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, staticVer_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, timezonebias_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, markettype_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt64(9, marketattr_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt64(10, numopentime_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt64(11, changeNum_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, market_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, staticDay_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, closestatus_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, ip_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, initTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, staticVer_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, timezonebias_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, markettype_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, marketattr_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, numopentime_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, changeNum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.dzhyun.proto.DzhyunMarketstatus.MarketStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dzhyun.proto.DzhyunMarketstatus.MarketStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunMarketstatus.MarketStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dzhyun.proto.DzhyunMarketstatus.MarketStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunMarketstatus.MarketStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dzhyun.proto.DzhyunMarketstatus.MarketStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunMarketstatus.MarketStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.dzhyun.proto.DzhyunMarketstatus.MarketStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunMarketstatus.MarketStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dzhyun.proto.DzhyunMarketstatus.MarketStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dzhyun.proto.DzhyunMarketstatus.MarketStatus prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dzhyun.MarketStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dzhyun.MarketStatus)
        com.dzhyun.proto.DzhyunMarketstatus.MarketStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dzhyun.proto.DzhyunMarketstatus.internal_static_dzhyun_MarketStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dzhyun.proto.DzhyunMarketstatus.internal_static_dzhyun_MarketStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dzhyun.proto.DzhyunMarketstatus.MarketStatus.class, com.dzhyun.proto.DzhyunMarketstatus.MarketStatus.Builder.class);
      }

      // Construct using com.dzhyun.proto.DzhyunMarketstatus.MarketStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        market_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        staticDay_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        closestatus_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        ip_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        initTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        staticVer_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        timezonebias_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        markettype_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        marketattr_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        numopentime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        changeNum_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dzhyun.proto.DzhyunMarketstatus.internal_static_dzhyun_MarketStatus_descriptor;
      }

      public com.dzhyun.proto.DzhyunMarketstatus.MarketStatus getDefaultInstanceForType() {
        return com.dzhyun.proto.DzhyunMarketstatus.MarketStatus.getDefaultInstance();
      }

      public com.dzhyun.proto.DzhyunMarketstatus.MarketStatus build() {
        com.dzhyun.proto.DzhyunMarketstatus.MarketStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dzhyun.proto.DzhyunMarketstatus.MarketStatus buildPartial() {
        com.dzhyun.proto.DzhyunMarketstatus.MarketStatus result = new com.dzhyun.proto.DzhyunMarketstatus.MarketStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.market_ = market_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.staticDay_ = staticDay_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.closestatus_ = closestatus_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.initTime_ = initTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.staticVer_ = staticVer_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.timezonebias_ = timezonebias_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.markettype_ = markettype_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.marketattr_ = marketattr_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.numopentime_ = numopentime_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.changeNum_ = changeNum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dzhyun.proto.DzhyunMarketstatus.MarketStatus) {
          return mergeFrom((com.dzhyun.proto.DzhyunMarketstatus.MarketStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dzhyun.proto.DzhyunMarketstatus.MarketStatus other) {
        if (other == com.dzhyun.proto.DzhyunMarketstatus.MarketStatus.getDefaultInstance()) return this;
        if (other.hasMarket()) {
          setMarket(other.getMarket());
        }
        if (other.hasStaticDay()) {
          setStaticDay(other.getStaticDay());
        }
        if (other.hasClosestatus()) {
          setClosestatus(other.getClosestatus());
        }
        if (other.hasIp()) {
          setIp(other.getIp());
        }
        if (other.hasInitTime()) {
          setInitTime(other.getInitTime());
        }
        if (other.hasStaticVer()) {
          setStaticVer(other.getStaticVer());
        }
        if (other.hasTimezonebias()) {
          setTimezonebias(other.getTimezonebias());
        }
        if (other.hasMarkettype()) {
          setMarkettype(other.getMarkettype());
        }
        if (other.hasMarketattr()) {
          setMarketattr(other.getMarketattr());
        }
        if (other.hasNumopentime()) {
          setNumopentime(other.getNumopentime());
        }
        if (other.hasChangeNum()) {
          setChangeNum(other.getChangeNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMarket()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dzhyun.proto.DzhyunMarketstatus.MarketStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dzhyun.proto.DzhyunMarketstatus.MarketStatus) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long market_ ;
      /**
       * <code>required int64 Market = 1;</code>
       */
      public boolean hasMarket() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 Market = 1;</code>
       */
      public long getMarket() {
        return market_;
      }
      /**
       * <code>required int64 Market = 1;</code>
       */
      public Builder setMarket(long value) {
        bitField0_ |= 0x00000001;
        market_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 Market = 1;</code>
       */
      public Builder clearMarket() {
        bitField0_ = (bitField0_ & ~0x00000001);
        market_ = 0L;
        onChanged();
        return this;
      }

      private long staticDay_ ;
      /**
       * <code>optional int64 Static_day = 2;</code>
       *
       * <pre>
       * static_day
       * </pre>
       */
      public boolean hasStaticDay() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 Static_day = 2;</code>
       *
       * <pre>
       * static_day
       * </pre>
       */
      public long getStaticDay() {
        return staticDay_;
      }
      /**
       * <code>optional int64 Static_day = 2;</code>
       *
       * <pre>
       * static_day
       * </pre>
       */
      public Builder setStaticDay(long value) {
        bitField0_ |= 0x00000002;
        staticDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Static_day = 2;</code>
       *
       * <pre>
       * static_day
       * </pre>
       */
      public Builder clearStaticDay() {
        bitField0_ = (bitField0_ & ~0x00000002);
        staticDay_ = 0L;
        onChanged();
        return this;
      }

      private long closestatus_ ;
      /**
       * <code>optional int64 Closestatus = 3;</code>
       *
       * <pre>
       * closestatus
       * </pre>
       */
      public boolean hasClosestatus() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 Closestatus = 3;</code>
       *
       * <pre>
       * closestatus
       * </pre>
       */
      public long getClosestatus() {
        return closestatus_;
      }
      /**
       * <code>optional int64 Closestatus = 3;</code>
       *
       * <pre>
       * closestatus
       * </pre>
       */
      public Builder setClosestatus(long value) {
        bitField0_ |= 0x00000004;
        closestatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Closestatus = 3;</code>
       *
       * <pre>
       * closestatus
       * </pre>
       */
      public Builder clearClosestatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        closestatus_ = 0L;
        onChanged();
        return this;
      }

      private long ip_ ;
      /**
       * <code>optional int64 Ip = 4;</code>
       *
       * <pre>
       * ip
       * </pre>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 Ip = 4;</code>
       *
       * <pre>
       * ip
       * </pre>
       */
      public long getIp() {
        return ip_;
      }
      /**
       * <code>optional int64 Ip = 4;</code>
       *
       * <pre>
       * ip
       * </pre>
       */
      public Builder setIp(long value) {
        bitField0_ |= 0x00000008;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Ip = 4;</code>
       *
       * <pre>
       * ip
       * </pre>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ip_ = 0L;
        onChanged();
        return this;
      }

      private long initTime_ ;
      /**
       * <code>optional int64 Init_time = 5;</code>
       *
       * <pre>
       * init_time
       * </pre>
       */
      public boolean hasInitTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 Init_time = 5;</code>
       *
       * <pre>
       * init_time
       * </pre>
       */
      public long getInitTime() {
        return initTime_;
      }
      /**
       * <code>optional int64 Init_time = 5;</code>
       *
       * <pre>
       * init_time
       * </pre>
       */
      public Builder setInitTime(long value) {
        bitField0_ |= 0x00000010;
        initTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Init_time = 5;</code>
       *
       * <pre>
       * init_time
       * </pre>
       */
      public Builder clearInitTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        initTime_ = 0L;
        onChanged();
        return this;
      }

      private long staticVer_ ;
      /**
       * <code>optional int64 Static_ver = 6;</code>
       *
       * <pre>
       * static_ver
       * </pre>
       */
      public boolean hasStaticVer() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 Static_ver = 6;</code>
       *
       * <pre>
       * static_ver
       * </pre>
       */
      public long getStaticVer() {
        return staticVer_;
      }
      /**
       * <code>optional int64 Static_ver = 6;</code>
       *
       * <pre>
       * static_ver
       * </pre>
       */
      public Builder setStaticVer(long value) {
        bitField0_ |= 0x00000020;
        staticVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Static_ver = 6;</code>
       *
       * <pre>
       * static_ver
       * </pre>
       */
      public Builder clearStaticVer() {
        bitField0_ = (bitField0_ & ~0x00000020);
        staticVer_ = 0L;
        onChanged();
        return this;
      }

      private long timezonebias_ ;
      /**
       * <code>optional int64 Timezonebias = 7;</code>
       *
       * <pre>
       * timezonebias
       * </pre>
       */
      public boolean hasTimezonebias() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int64 Timezonebias = 7;</code>
       *
       * <pre>
       * timezonebias
       * </pre>
       */
      public long getTimezonebias() {
        return timezonebias_;
      }
      /**
       * <code>optional int64 Timezonebias = 7;</code>
       *
       * <pre>
       * timezonebias
       * </pre>
       */
      public Builder setTimezonebias(long value) {
        bitField0_ |= 0x00000040;
        timezonebias_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Timezonebias = 7;</code>
       *
       * <pre>
       * timezonebias
       * </pre>
       */
      public Builder clearTimezonebias() {
        bitField0_ = (bitField0_ & ~0x00000040);
        timezonebias_ = 0L;
        onChanged();
        return this;
      }

      private long markettype_ ;
      /**
       * <code>optional int64 Markettype = 8;</code>
       *
       * <pre>
       * markettype
       * </pre>
       */
      public boolean hasMarkettype() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int64 Markettype = 8;</code>
       *
       * <pre>
       * markettype
       * </pre>
       */
      public long getMarkettype() {
        return markettype_;
      }
      /**
       * <code>optional int64 Markettype = 8;</code>
       *
       * <pre>
       * markettype
       * </pre>
       */
      public Builder setMarkettype(long value) {
        bitField0_ |= 0x00000080;
        markettype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Markettype = 8;</code>
       *
       * <pre>
       * markettype
       * </pre>
       */
      public Builder clearMarkettype() {
        bitField0_ = (bitField0_ & ~0x00000080);
        markettype_ = 0L;
        onChanged();
        return this;
      }

      private long marketattr_ ;
      /**
       * <code>optional int64 Marketattr = 9;</code>
       *
       * <pre>
       * marketattr
       * </pre>
       */
      public boolean hasMarketattr() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int64 Marketattr = 9;</code>
       *
       * <pre>
       * marketattr
       * </pre>
       */
      public long getMarketattr() {
        return marketattr_;
      }
      /**
       * <code>optional int64 Marketattr = 9;</code>
       *
       * <pre>
       * marketattr
       * </pre>
       */
      public Builder setMarketattr(long value) {
        bitField0_ |= 0x00000100;
        marketattr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Marketattr = 9;</code>
       *
       * <pre>
       * marketattr
       * </pre>
       */
      public Builder clearMarketattr() {
        bitField0_ = (bitField0_ & ~0x00000100);
        marketattr_ = 0L;
        onChanged();
        return this;
      }

      private long numopentime_ ;
      /**
       * <code>optional int64 Numopentime = 10;</code>
       *
       * <pre>
       * numopentime
       * </pre>
       */
      public boolean hasNumopentime() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int64 Numopentime = 10;</code>
       *
       * <pre>
       * numopentime
       * </pre>
       */
      public long getNumopentime() {
        return numopentime_;
      }
      /**
       * <code>optional int64 Numopentime = 10;</code>
       *
       * <pre>
       * numopentime
       * </pre>
       */
      public Builder setNumopentime(long value) {
        bitField0_ |= 0x00000200;
        numopentime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Numopentime = 10;</code>
       *
       * <pre>
       * numopentime
       * </pre>
       */
      public Builder clearNumopentime() {
        bitField0_ = (bitField0_ & ~0x00000200);
        numopentime_ = 0L;
        onChanged();
        return this;
      }

      private long changeNum_ ;
      /**
       * <code>optional int64 Change_num = 11;</code>
       *
       * <pre>
       * change_num
       * </pre>
       */
      public boolean hasChangeNum() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int64 Change_num = 11;</code>
       *
       * <pre>
       * change_num
       * </pre>
       */
      public long getChangeNum() {
        return changeNum_;
      }
      /**
       * <code>optional int64 Change_num = 11;</code>
       *
       * <pre>
       * change_num
       * </pre>
       */
      public Builder setChangeNum(long value) {
        bitField0_ |= 0x00000400;
        changeNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Change_num = 11;</code>
       *
       * <pre>
       * change_num
       * </pre>
       */
      public Builder clearChangeNum() {
        bitField0_ = (bitField0_ & ~0x00000400);
        changeNum_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dzhyun.MarketStatus)
    }

    static {
      defaultInstance = new MarketStatus(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:dzhyun.MarketStatus)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dzhyun_MarketStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dzhyun_MarketStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031dzhyun.marketstatus.proto\022\006dzhyun\"\341\001\n\014" +
      "MarketStatus\022\016\n\006Market\030\001 \002(\003\022\022\n\nStatic_d" +
      "ay\030\002 \001(\003\022\023\n\013Closestatus\030\003 \001(\003\022\n\n\002Ip\030\004 \001(" +
      "\003\022\021\n\tInit_time\030\005 \001(\003\022\022\n\nStatic_ver\030\006 \001(\003" +
      "\022\024\n\014Timezonebias\030\007 \001(\003\022\022\n\nMarkettype\030\010 \001" +
      "(\003\022\022\n\nMarketattr\030\t \001(\003\022\023\n\013Numopentime\030\n " +
      "\001(\003\022\022\n\nChange_num\030\013 \001(\003B\022\n\020com.dzhyun.pr" +
      "oto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_dzhyun_MarketStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dzhyun_MarketStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_dzhyun_MarketStatus_descriptor,
        new java.lang.String[] { "Market", "StaticDay", "Closestatus", "Ip", "InitTime", "StaticVer", "Timezonebias", "Markettype", "Marketattr", "Numopentime", "ChangeNum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
