// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: indicate.proto

#import "J2ObjC_source.h"
#import "com/dzhyun/proto/DzhIndicate.h"
#import "com/google/protobuf/Descriptors_PackagePrivate.h"
#import "com/google/protobuf/ExtensionRegistry.h"
#import "com/google/protobuf/GeneratedMessage_PackagePrivate.h"
#import "com/google/protobuf/RepeatedField.h"
#import "java/lang/IllegalArgumentException.h"

#pragma GCC diagnostic ignored "-Wprotocol"
#pragma clang diagnostic ignored "-Wprotocol"
#pragma GCC diagnostic ignored "-Wincomplete-implementation"
#pragma clang diagnostic ignored "-Wincomplete-implementation"

@implementation ComDzhyunProtoDzhIndicate

+ (void)registerAllExtensionsWithComGoogleProtobufExtensionRegistry:(ComGoogleProtobufExtensionRegistry *)extensionRegistry {
  ComDzhyunProtoDzhIndicate_registerAllExtensionsWithComGoogleProtobufExtensionRegistry_(extensionRegistry);
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhIndicate)

void ComDzhyunProtoDzhIndicate_registerAllExtensionsWithComGoogleProtobufExtensionRegistry_(ComGoogleProtobufExtensionRegistry *extensionRegistry) {
}

J2OBJC_INITIALIZED_DEFN(ComDzhyunProtoDzhIndicate_IndiTypeEnum)

ComDzhyunProtoDzhIndicate_IndiTypeEnum *ComDzhyunProtoDzhIndicate_IndiTypeEnum_values_[9];

static ComGoogleProtobufDescriptors_EnumDescriptor *ComDzhyunProtoDzhIndicate_IndiTypeEnum_descriptor = nil;

@implementation ComDzhyunProtoDzhIndicate_IndiTypeEnum

- (id)initWithName:(NSString *)name withIndex:(jint)index withValue:(jint)value {
  if (self = [super initWithNSString:name withInt:index]) {
    value_ = value;
  }
  return self;
}

+ (void)initialize {
  if (self == [ComDzhyunProtoDzhIndicate_IndiTypeEnum class]) {
    ComDzhyunProtoDzhIndicate_IndiTypeEnum_INDITYPE_EXPLORER = [[ComDzhyunProtoDzhIndicate_IndiTypeEnum alloc] initWithName:@"INDITYPE_EXPLORER" withIndex:0 withValue:0];
    ComDzhyunProtoDzhIndicate_IndiTypeEnum_INDITYPE_SYSTEST = [[ComDzhyunProtoDzhIndicate_IndiTypeEnum alloc] initWithName:@"INDITYPE_SYSTEST" withIndex:1 withValue:1];
    ComDzhyunProtoDzhIndicate_IndiTypeEnum_INDITYPE_MAIN_PICT = [[ComDzhyunProtoDzhIndicate_IndiTypeEnum alloc] initWithName:@"INDITYPE_MAIN_PICT" withIndex:2 withValue:2];
    ComDzhyunProtoDzhIndicate_IndiTypeEnum_INDITYPE_MAIN_ADD = [[ComDzhyunProtoDzhIndicate_IndiTypeEnum alloc] initWithName:@"INDITYPE_MAIN_ADD" withIndex:3 withValue:3];
    ComDzhyunProtoDzhIndicate_IndiTypeEnum_INDITYPE_SUB_PICT = [[ComDzhyunProtoDzhIndicate_IndiTypeEnum alloc] initWithName:@"INDITYPE_SUB_PICT" withIndex:4 withValue:4];
    ComDzhyunProtoDzhIndicate_IndiTypeEnum_INDITYPE_PAINT_IT = [[ComDzhyunProtoDzhIndicate_IndiTypeEnum alloc] initWithName:@"INDITYPE_PAINT_IT" withIndex:5 withValue:5];
    ComDzhyunProtoDzhIndicate_IndiTypeEnum_INDITYPE_TEMP_INDI = [[ComDzhyunProtoDzhIndicate_IndiTypeEnum alloc] initWithName:@"INDITYPE_TEMP_INDI" withIndex:6 withValue:6];
    ComDzhyunProtoDzhIndicate_IndiTypeEnum_INDITYPE_TECHNIQUE = [[ComDzhyunProtoDzhIndicate_IndiTypeEnum alloc] initWithName:@"INDITYPE_TECHNIQUE" withIndex:7 withValue:7];
    ComDzhyunProtoDzhIndicate_IndiTypeEnum_INDITYPE_UNKNOWN = [[ComDzhyunProtoDzhIndicate_IndiTypeEnum alloc] initWithName:@"INDITYPE_UNKNOWN" withIndex:8 withValue:8];
    ComDzhyunProtoDzhIndicate_IndiTypeEnum_descriptor = CGPNewEnumDescriptor(self, 9, ComDzhyunProtoDzhIndicate_IndiTypeEnum_values_);
    J2OBJC_SET_INITIALIZED(ComDzhyunProtoDzhIndicate_IndiTypeEnum)
  }
}

+ (IOSObjectArray *)values {
  return ComDzhyunProtoDzhIndicate_IndiTypeEnum_values();}

+ (ComDzhyunProtoDzhIndicate_IndiTypeEnum *)valueOfWithNSString:(NSString *)name {
  return ComDzhyunProtoDzhIndicate_IndiTypeEnum_valueOfWithNSString_(name);
}

+ (ComDzhyunProtoDzhIndicate_IndiTypeEnum *)valueOfWithInt:(jint)value {
  return ComDzhyunProtoDzhIndicate_IndiTypeEnum_valueOfWithInt_(value);
}

- (jint)getNumber {
  return value_;
}

+ (ComGoogleProtobufDescriptors_EnumDescriptor *)getDescriptor {
  return ComDzhyunProtoDzhIndicate_IndiTypeEnum_descriptor;
}

- (ComGoogleProtobufDescriptors_EnumValueDescriptor *)getValueDescriptor {
  return ComDzhyunProtoDzhIndicate_IndiTypeEnum_descriptor->values_->buffer_[[self ordinal]];
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhIndicate_IndiTypeEnum)

IOSObjectArray *ComDzhyunProtoDzhIndicate_IndiTypeEnum_values() {
  ComDzhyunProtoDzhIndicate_IndiTypeEnum_initialize();  return [IOSObjectArray arrayWithObjects:ComDzhyunProtoDzhIndicate_IndiTypeEnum_values_ count:9 type:ComDzhyunProtoDzhIndicate_IndiTypeEnum_class_()];
}

ComDzhyunProtoDzhIndicate_IndiTypeEnum *ComDzhyunProtoDzhIndicate_IndiTypeEnum_valueOfWithNSString_(NSString *name) {
  ComDzhyunProtoDzhIndicate_IndiTypeEnum_initialize();  for (jint i = 0; i < 9; i++) {
    ComDzhyunProtoDzhIndicate_IndiTypeEnum *e = ComDzhyunProtoDzhIndicate_IndiTypeEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc] initWithNSString:name] autorelease];
}

ComDzhyunProtoDzhIndicate_IndiTypeEnum *ComDzhyunProtoDzhIndicate_IndiTypeEnum_valueOfWithInt_(jint value) {
  ComDzhyunProtoDzhIndicate_IndiTypeEnum_initialize();  for (jint i = 0; i < 9; i++) {
    ComDzhyunProtoDzhIndicate_IndiTypeEnum *e = ComDzhyunProtoDzhIndicate_IndiTypeEnum_values_[i];
    if (value == [e getNumber]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc]
      initWithNSString:[NSString stringWithFormat:@"%d", value]] autorelease];
}


J2OBJC_INITIALIZED_DEFN(ComDzhyunProtoDzhIndicate_IndiTextTypeEnum)

ComDzhyunProtoDzhIndicate_IndiTextTypeEnum *ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_values_[3];

static ComGoogleProtobufDescriptors_EnumDescriptor *ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_descriptor = nil;

@implementation ComDzhyunProtoDzhIndicate_IndiTextTypeEnum

- (id)initWithName:(NSString *)name withIndex:(jint)index withValue:(jint)value {
  if (self = [super initWithNSString:name withInt:index]) {
    value_ = value;
  }
  return self;
}

+ (void)initialize {
  if (self == [ComDzhyunProtoDzhIndicate_IndiTextTypeEnum class]) {
    ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_INDTTEXTTYPE_FORMULA = [[ComDzhyunProtoDzhIndicate_IndiTextTypeEnum alloc] initWithName:@"INDTTEXTTYPE_FORMULA" withIndex:0 withValue:0];
    ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_INDTTEXTTYPE_LUA = [[ComDzhyunProtoDzhIndicate_IndiTextTypeEnum alloc] initWithName:@"INDTTEXTTYPE_LUA" withIndex:1 withValue:1];
    ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_INDTTEXTTYPE_UNKNOWN = [[ComDzhyunProtoDzhIndicate_IndiTextTypeEnum alloc] initWithName:@"INDTTEXTTYPE_UNKNOWN" withIndex:2 withValue:2];
    ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_descriptor = CGPNewEnumDescriptor(self, 3, ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_values_);
    J2OBJC_SET_INITIALIZED(ComDzhyunProtoDzhIndicate_IndiTextTypeEnum)
  }
}

+ (IOSObjectArray *)values {
  return ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_values();}

+ (ComDzhyunProtoDzhIndicate_IndiTextTypeEnum *)valueOfWithNSString:(NSString *)name {
  return ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_valueOfWithNSString_(name);
}

+ (ComDzhyunProtoDzhIndicate_IndiTextTypeEnum *)valueOfWithInt:(jint)value {
  return ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_valueOfWithInt_(value);
}

- (jint)getNumber {
  return value_;
}

+ (ComGoogleProtobufDescriptors_EnumDescriptor *)getDescriptor {
  return ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_descriptor;
}

- (ComGoogleProtobufDescriptors_EnumValueDescriptor *)getValueDescriptor {
  return ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_descriptor->values_->buffer_[[self ordinal]];
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhIndicate_IndiTextTypeEnum)

IOSObjectArray *ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_values() {
  ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_initialize();  return [IOSObjectArray arrayWithObjects:ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_values_ count:3 type:ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_class_()];
}

ComDzhyunProtoDzhIndicate_IndiTextTypeEnum *ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_valueOfWithNSString_(NSString *name) {
  ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_initialize();  for (jint i = 0; i < 3; i++) {
    ComDzhyunProtoDzhIndicate_IndiTextTypeEnum *e = ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc] initWithNSString:name] autorelease];
}

ComDzhyunProtoDzhIndicate_IndiTextTypeEnum *ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_valueOfWithInt_(jint value) {
  ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_initialize();  for (jint i = 0; i < 3; i++) {
    ComDzhyunProtoDzhIndicate_IndiTextTypeEnum *e = ComDzhyunProtoDzhIndicate_IndiTextTypeEnum_values_[i];
    if (value == [e getNumber]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc]
      initWithNSString:[NSString stringWithFormat:@"%d", value]] autorelease];
}


J2OBJC_INITIALIZED_DEFN(ComDzhyunProtoDzhIndicate_IndiParam);

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhIndicate_IndiParam_descriptor_;

@implementation ComDzhyunProtoDzhIndicate_IndiParam

typedef struct ComDzhyunProtoDzhIndicate_IndiParam_Storage {
  uint32_t hasBits[1];
  NSString *name_;
  double defaultValue_;
  double minValue_;
  double maxValue_;
  double step_;
} ComDzhyunProtoDzhIndicate_IndiParam_Storage;

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return ComDzhyunProtoDzhIndicate_IndiParam_descriptor_;
}

+ (void)initialize {
  if (self == [ComDzhyunProtoDzhIndicate_IndiParam class]) {
    static CGPFieldData fields[] = {
      {
        .name = "name",
        .javaName = "Name",
        .number = 1,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_STRING,
        .defaultValue.valueId = @"",
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_IndiParam_Storage, name_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_IndiParam",
        .optionsData = NULL,
      },
      {
        .name = "defaultValue",
        .javaName = "DefaultValue",
        .number = 2,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_DOUBLE,
        .defaultValue.valueDouble = 0,
        .hasBitIndex = 1,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_IndiParam_Storage, defaultValue_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_IndiParam",
        .optionsData = NULL,
      },
      {
        .name = "minValue",
        .javaName = "MinValue",
        .number = 3,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_DOUBLE,
        .defaultValue.valueDouble = 0,
        .hasBitIndex = 2,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_IndiParam_Storage, minValue_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_IndiParam",
        .optionsData = NULL,
      },
      {
        .name = "maxValue",
        .javaName = "MaxValue",
        .number = 4,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_DOUBLE,
        .defaultValue.valueDouble = 0,
        .hasBitIndex = 3,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_IndiParam_Storage, maxValue_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_IndiParam",
        .optionsData = NULL,
      },
      {
        .name = "step",
        .javaName = "Step",
        .number = 5,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_DOUBLE,
        .defaultValue.valueDouble = 0,
        .hasBitIndex = 4,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_IndiParam_Storage, step_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_IndiParam",
        .optionsData = NULL,
      },
    };
    CGPInitDescriptor(&ComDzhyunProtoDzhIndicate_IndiParam_descriptor_, self, [ComDzhyunProtoDzhIndicate_IndiParam_Builder class], 0, sizeof(ComDzhyunProtoDzhIndicate_IndiParam_Storage), 5, fields);
    J2OBJC_SET_INITIALIZED(ComDzhyunProtoDzhIndicate_IndiParam)
  }
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhIndicate_IndiParam)

ComDzhyunProtoDzhIndicate_IndiParam *ComDzhyunProtoDzhIndicate_IndiParam_getDefaultInstance() {
  ComDzhyunProtoDzhIndicate_IndiParam_initialize();
  return (ComDzhyunProtoDzhIndicate_IndiParam *)[CGPNewMessage(ComDzhyunProtoDzhIndicate_IndiParam_descriptor_) autorelease];
}

ComDzhyunProtoDzhIndicate_IndiParam_Builder *ComDzhyunProtoDzhIndicate_IndiParam_newBuilder() {
  ComDzhyunProtoDzhIndicate_IndiParam_initialize();
  return (ComDzhyunProtoDzhIndicate_IndiParam_Builder *)[CGPNewBuilder(ComDzhyunProtoDzhIndicate_IndiParam_descriptor_) autorelease];
}

ComDzhyunProtoDzhIndicate_IndiParam_Builder *ComDzhyunProtoDzhIndicate_IndiParam_newBuilderWithComDzhyunProtoDzhIndicate_IndiParam_(ComDzhyunProtoDzhIndicate_IndiParam *message) {
  ComDzhyunProtoDzhIndicate_IndiParam_initialize();
  return (ComDzhyunProtoDzhIndicate_IndiParam_Builder *)CGPBuilderFromPrototype(ComDzhyunProtoDzhIndicate_IndiParam_descriptor_, message);
}

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhIndicate_IndiParam_getDescriptor() {
  ComDzhyunProtoDzhIndicate_IndiParam_initialize();
  return ComDzhyunProtoDzhIndicate_IndiParam_descriptor_;
}

ComDzhyunProtoDzhIndicate_IndiParam *ComDzhyunProtoDzhIndicate_IndiParam_parseFromWithByteArray_withComGoogleProtobufExtensionRegistryLite_(IOSByteArray *bytes, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhIndicate_IndiParam_initialize();
  return (ComDzhyunProtoDzhIndicate_IndiParam *)CGPParseFromByteArray(ComDzhyunProtoDzhIndicate_IndiParam_descriptor_, bytes, registry);
}

ComDzhyunProtoDzhIndicate_IndiParam *ComDzhyunProtoDzhIndicate_IndiParam_parseFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhIndicate_IndiParam_initialize();
  return (ComDzhyunProtoDzhIndicate_IndiParam *)CGPParseFromInputStream(ComDzhyunProtoDzhIndicate_IndiParam_descriptor_, input, registry);
}
ComDzhyunProtoDzhIndicate_IndiParam *ComDzhyunProtoDzhIndicate_IndiParam_parseDelimitedFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhIndicate_IndiParam_initialize();
  return (ComDzhyunProtoDzhIndicate_IndiParam *)CGPParseDelimitedFromInputStream(ComDzhyunProtoDzhIndicate_IndiParam_descriptor_, input, registry);
}

@implementation ComDzhyunProtoDzhIndicate_IndiParam_Builder

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return [ComDzhyunProtoDzhIndicate_IndiParam getDescriptor];
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhIndicate_IndiParam_Builder)
J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhIndicate_IndiParamOrBuilder)

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhIndicate_IndiParam_Builder_getDescriptor() {
  ComDzhyunProtoDzhIndicate_IndiParam_initialize();
  return ComDzhyunProtoDzhIndicate_IndiParam_descriptor_;
}

J2OBJC_INITIALIZED_DEFN(ComDzhyunProtoDzhIndicate_IndiOutput);

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhIndicate_IndiOutput_descriptor_;

@implementation ComDzhyunProtoDzhIndicate_IndiOutput

typedef struct ComDzhyunProtoDzhIndicate_IndiOutput_Storage {
  uint32_t hasBits[1];
  NSString *name_;
  int outtype_;
  int move_;
  int attr_;
  int color_;
  int varpos_;
  int attrex_;
} ComDzhyunProtoDzhIndicate_IndiOutput_Storage;

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return ComDzhyunProtoDzhIndicate_IndiOutput_descriptor_;
}

+ (void)initialize {
  if (self == [ComDzhyunProtoDzhIndicate_IndiOutput class]) {
    static CGPFieldData fields[] = {
      {
        .name = "name",
        .javaName = "Name",
        .number = 1,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_STRING,
        .defaultValue.valueId = @"",
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_IndiOutput_Storage, name_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_IndiOutput",
        .optionsData = NULL,
      },
      {
        .name = "outtype",
        .javaName = "Outtype",
        .number = 2,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_UINT32,
        .defaultValue.valueInt = 0,
        .hasBitIndex = 1,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_IndiOutput_Storage, outtype_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_IndiOutput",
        .optionsData = NULL,
      },
      {
        .name = "move",
        .javaName = "Move",
        .number = 3,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_UINT32,
        .defaultValue.valueInt = 0,
        .hasBitIndex = 2,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_IndiOutput_Storage, move_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_IndiOutput",
        .optionsData = NULL,
      },
      {
        .name = "attr",
        .javaName = "Attr",
        .number = 4,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_UINT32,
        .defaultValue.valueInt = 0,
        .hasBitIndex = 3,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_IndiOutput_Storage, attr_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_IndiOutput",
        .optionsData = NULL,
      },
      {
        .name = "color",
        .javaName = "Color",
        .number = 5,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_UINT32,
        .defaultValue.valueInt = 0,
        .hasBitIndex = 4,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_IndiOutput_Storage, color_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_IndiOutput",
        .optionsData = NULL,
      },
      {
        .name = "varpos",
        .javaName = "Varpos",
        .number = 6,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_UINT32,
        .defaultValue.valueInt = 0,
        .hasBitIndex = 5,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_IndiOutput_Storage, varpos_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_IndiOutput",
        .optionsData = NULL,
      },
      {
        .name = "attrex",
        .javaName = "Attrex",
        .number = 7,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_UINT32,
        .defaultValue.valueInt = 0,
        .hasBitIndex = 6,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_IndiOutput_Storage, attrex_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_IndiOutput",
        .optionsData = NULL,
      },
    };
    CGPInitDescriptor(&ComDzhyunProtoDzhIndicate_IndiOutput_descriptor_, self, [ComDzhyunProtoDzhIndicate_IndiOutput_Builder class], 0, sizeof(ComDzhyunProtoDzhIndicate_IndiOutput_Storage), 7, fields);
    J2OBJC_SET_INITIALIZED(ComDzhyunProtoDzhIndicate_IndiOutput)
  }
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhIndicate_IndiOutput)

ComDzhyunProtoDzhIndicate_IndiOutput *ComDzhyunProtoDzhIndicate_IndiOutput_getDefaultInstance() {
  ComDzhyunProtoDzhIndicate_IndiOutput_initialize();
  return (ComDzhyunProtoDzhIndicate_IndiOutput *)[CGPNewMessage(ComDzhyunProtoDzhIndicate_IndiOutput_descriptor_) autorelease];
}

ComDzhyunProtoDzhIndicate_IndiOutput_Builder *ComDzhyunProtoDzhIndicate_IndiOutput_newBuilder() {
  ComDzhyunProtoDzhIndicate_IndiOutput_initialize();
  return (ComDzhyunProtoDzhIndicate_IndiOutput_Builder *)[CGPNewBuilder(ComDzhyunProtoDzhIndicate_IndiOutput_descriptor_) autorelease];
}

ComDzhyunProtoDzhIndicate_IndiOutput_Builder *ComDzhyunProtoDzhIndicate_IndiOutput_newBuilderWithComDzhyunProtoDzhIndicate_IndiOutput_(ComDzhyunProtoDzhIndicate_IndiOutput *message) {
  ComDzhyunProtoDzhIndicate_IndiOutput_initialize();
  return (ComDzhyunProtoDzhIndicate_IndiOutput_Builder *)CGPBuilderFromPrototype(ComDzhyunProtoDzhIndicate_IndiOutput_descriptor_, message);
}

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhIndicate_IndiOutput_getDescriptor() {
  ComDzhyunProtoDzhIndicate_IndiOutput_initialize();
  return ComDzhyunProtoDzhIndicate_IndiOutput_descriptor_;
}

ComDzhyunProtoDzhIndicate_IndiOutput *ComDzhyunProtoDzhIndicate_IndiOutput_parseFromWithByteArray_withComGoogleProtobufExtensionRegistryLite_(IOSByteArray *bytes, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhIndicate_IndiOutput_initialize();
  return (ComDzhyunProtoDzhIndicate_IndiOutput *)CGPParseFromByteArray(ComDzhyunProtoDzhIndicate_IndiOutput_descriptor_, bytes, registry);
}

ComDzhyunProtoDzhIndicate_IndiOutput *ComDzhyunProtoDzhIndicate_IndiOutput_parseFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhIndicate_IndiOutput_initialize();
  return (ComDzhyunProtoDzhIndicate_IndiOutput *)CGPParseFromInputStream(ComDzhyunProtoDzhIndicate_IndiOutput_descriptor_, input, registry);
}
ComDzhyunProtoDzhIndicate_IndiOutput *ComDzhyunProtoDzhIndicate_IndiOutput_parseDelimitedFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhIndicate_IndiOutput_initialize();
  return (ComDzhyunProtoDzhIndicate_IndiOutput *)CGPParseDelimitedFromInputStream(ComDzhyunProtoDzhIndicate_IndiOutput_descriptor_, input, registry);
}

@implementation ComDzhyunProtoDzhIndicate_IndiOutput_Builder

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return [ComDzhyunProtoDzhIndicate_IndiOutput getDescriptor];
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhIndicate_IndiOutput_Builder)
J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhIndicate_IndiOutputOrBuilder)

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhIndicate_IndiOutput_Builder_getDescriptor() {
  ComDzhyunProtoDzhIndicate_IndiOutput_initialize();
  return ComDzhyunProtoDzhIndicate_IndiOutput_descriptor_;
}

J2OBJC_INITIALIZED_DEFN(ComDzhyunProtoDzhIndicate_Indicate);

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhIndicate_Indicate_descriptor_;

@implementation ComDzhyunProtoDzhIndicate_Indicate

typedef struct ComDzhyunProtoDzhIndicate_Indicate_Storage {
  uint32_t hasBits[1];
  NSString *name_;
  NSString *desc_;
  NSString *usage_;
  NSString *paramWizard_;
  NSString *sugesstGroup_;
  NSString *formula_;
  int time_;
  ComDzhyunProtoDzhIndicate_IndiTypeEnum *indiType_;
  ComDzhyunProtoDzhIndicate_IndiTextTypeEnum *textType_;
  int version_;
  int attrib_;
  int defaultType_;
  NSString *byteCode_;
  BOOL frequently_;
  BOOL isSelf_;
  CGPRepeatedField extraData_;
  CGPRepeatedField params_;
  CGPRepeatedField outputs_;
} ComDzhyunProtoDzhIndicate_Indicate_Storage;

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return ComDzhyunProtoDzhIndicate_Indicate_descriptor_;
}

+ (void)initialize {
  if (self == [ComDzhyunProtoDzhIndicate_Indicate class]) {
    static CGPFieldData fields[] = {
      {
        .name = "name",
        .javaName = "Name",
        .number = 1,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_STRING,
        .defaultValue.valueId = @"",
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_Indicate_Storage, name_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_Indicate",
        .optionsData = NULL,
      },
      {
        .name = "desc",
        .javaName = "Desc",
        .number = 2,
        .flags = 0,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_STRING,
        .defaultValue.valueId = @"",
        .hasBitIndex = 1,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_Indicate_Storage, desc_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_Indicate",
        .optionsData = NULL,
      },
      {
        .name = "usage",
        .javaName = "Usage",
        .number = 3,
        .flags = 0,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_STRING,
        .defaultValue.valueId = @"",
        .hasBitIndex = 2,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_Indicate_Storage, usage_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_Indicate",
        .optionsData = NULL,
      },
      {
        .name = "paramWizard",
        .javaName = "ParamWizard",
        .number = 4,
        .flags = 0,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_STRING,
        .defaultValue.valueId = @"",
        .hasBitIndex = 3,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_Indicate_Storage, paramWizard_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_Indicate",
        .optionsData = NULL,
      },
      {
        .name = "sugesstGroup",
        .javaName = "SugesstGroup",
        .number = 5,
        .flags = 0,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_STRING,
        .defaultValue.valueId = @"",
        .hasBitIndex = 4,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_Indicate_Storage, sugesstGroup_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_Indicate",
        .optionsData = NULL,
      },
      {
        .name = "formula",
        .javaName = "Formula",
        .number = 6,
        .flags = 0,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_STRING,
        .defaultValue.valueId = @"",
        .hasBitIndex = 5,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_Indicate_Storage, formula_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_Indicate",
        .optionsData = NULL,
      },
      {
        .name = "time",
        .javaName = "Time",
        .number = 7,
        .flags = 0,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_UINT32,
        .defaultValue.valueInt = 0,
        .hasBitIndex = 6,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_Indicate_Storage, time_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_Indicate",
        .optionsData = NULL,
      },
      {
        .name = "indiType",
        .javaName = "IndiType",
        .number = 8,
        .flags = 0,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_ENUM,
        .defaultValue.valueInt = ComDzhyunProtoDzhIndicate_IndiType_INDITYPE_EXPLORER,
        .hasBitIndex = 7,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_Indicate_Storage, indiType_),
        .className = "ComDzhyunProtoDzhIndicate_IndiTypeEnum",
        .containingType = "ComDzhyunProtoDzhIndicate_Indicate",
        .optionsData = NULL,
      },
      {
        .name = "textType",
        .javaName = "TextType",
        .number = 9,
        .flags = 0,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_ENUM,
        .defaultValue.valueInt = ComDzhyunProtoDzhIndicate_IndiTextType_INDTTEXTTYPE_FORMULA,
        .hasBitIndex = 8,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_Indicate_Storage, textType_),
        .className = "ComDzhyunProtoDzhIndicate_IndiTextTypeEnum",
        .containingType = "ComDzhyunProtoDzhIndicate_Indicate",
        .optionsData = NULL,
      },
      {
        .name = "version",
        .javaName = "Version",
        .number = 10,
        .flags = 0,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_UINT32,
        .defaultValue.valueInt = 0,
        .hasBitIndex = 9,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_Indicate_Storage, version_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_Indicate",
        .optionsData = NULL,
      },
      {
        .name = "attrib",
        .javaName = "Attrib",
        .number = 11,
        .flags = 0,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_UINT32,
        .defaultValue.valueInt = 0,
        .hasBitIndex = 10,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_Indicate_Storage, attrib_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_Indicate",
        .optionsData = NULL,
      },
      {
        .name = "defaultType",
        .javaName = "DefaultType",
        .number = 12,
        .flags = 0,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_UINT32,
        .defaultValue.valueInt = 0,
        .hasBitIndex = 11,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_Indicate_Storage, defaultType_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_Indicate",
        .optionsData = NULL,
      },
      {
        .name = "byteCode",
        .javaName = "ByteCode",
        .number = 13,
        .flags = 0,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_STRING,
        .defaultValue.valueId = @"",
        .hasBitIndex = 12,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_Indicate_Storage, byteCode_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_Indicate",
        .optionsData = NULL,
      },
      {
        .name = "frequently",
        .javaName = "Frequently",
        .number = 14,
        .flags = 0,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_BOOL,
        .defaultValue.valueBool = NO,
        .hasBitIndex = 13,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_Indicate_Storage, frequently_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_Indicate",
        .optionsData = NULL,
      },
      {
        .name = "isSelf",
        .javaName = "IsSelf",
        .number = 15,
        .flags = 0,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_BOOL,
        .defaultValue.valueBool = NO,
        .hasBitIndex = 14,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_Indicate_Storage, isSelf_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_Indicate",
        .optionsData = NULL,
      },
      {
        .name = "extraData",
        .javaName = "ExtraData",
        .number = 16,
        .flags = CGPFieldFlagRepeated,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_DOUBLE,
        .defaultValue.valueId = nil,
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_Indicate_Storage, extraData_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhIndicate_Indicate",
        .optionsData = NULL,
      },
      {
        .name = "params",
        .javaName = "Params",
        .number = 17,
        .flags = CGPFieldFlagRepeated,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_MESSAGE,
        .defaultValue.valueId = nil,
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_Indicate_Storage, params_),
        .className = "ComDzhyunProtoDzhIndicate_IndiParam",
        .containingType = "ComDzhyunProtoDzhIndicate_Indicate",
        .optionsData = NULL,
      },
      {
        .name = "outputs",
        .javaName = "Outputs",
        .number = 18,
        .flags = CGPFieldFlagRepeated,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_MESSAGE,
        .defaultValue.valueId = nil,
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_Indicate_Storage, outputs_),
        .className = "ComDzhyunProtoDzhIndicate_IndiOutput",
        .containingType = "ComDzhyunProtoDzhIndicate_Indicate",
        .optionsData = NULL,
      },
    };
    CGPInitDescriptor(&ComDzhyunProtoDzhIndicate_Indicate_descriptor_, self, [ComDzhyunProtoDzhIndicate_Indicate_Builder class], 0, sizeof(ComDzhyunProtoDzhIndicate_Indicate_Storage), 18, fields);
    J2OBJC_SET_INITIALIZED(ComDzhyunProtoDzhIndicate_Indicate)
  }
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhIndicate_Indicate)

ComDzhyunProtoDzhIndicate_Indicate *ComDzhyunProtoDzhIndicate_Indicate_getDefaultInstance() {
  ComDzhyunProtoDzhIndicate_Indicate_initialize();
  return (ComDzhyunProtoDzhIndicate_Indicate *)[CGPNewMessage(ComDzhyunProtoDzhIndicate_Indicate_descriptor_) autorelease];
}

ComDzhyunProtoDzhIndicate_Indicate_Builder *ComDzhyunProtoDzhIndicate_Indicate_newBuilder() {
  ComDzhyunProtoDzhIndicate_Indicate_initialize();
  return (ComDzhyunProtoDzhIndicate_Indicate_Builder *)[CGPNewBuilder(ComDzhyunProtoDzhIndicate_Indicate_descriptor_) autorelease];
}

ComDzhyunProtoDzhIndicate_Indicate_Builder *ComDzhyunProtoDzhIndicate_Indicate_newBuilderWithComDzhyunProtoDzhIndicate_Indicate_(ComDzhyunProtoDzhIndicate_Indicate *message) {
  ComDzhyunProtoDzhIndicate_Indicate_initialize();
  return (ComDzhyunProtoDzhIndicate_Indicate_Builder *)CGPBuilderFromPrototype(ComDzhyunProtoDzhIndicate_Indicate_descriptor_, message);
}

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhIndicate_Indicate_getDescriptor() {
  ComDzhyunProtoDzhIndicate_Indicate_initialize();
  return ComDzhyunProtoDzhIndicate_Indicate_descriptor_;
}

ComDzhyunProtoDzhIndicate_Indicate *ComDzhyunProtoDzhIndicate_Indicate_parseFromWithByteArray_withComGoogleProtobufExtensionRegistryLite_(IOSByteArray *bytes, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhIndicate_Indicate_initialize();
  return (ComDzhyunProtoDzhIndicate_Indicate *)CGPParseFromByteArray(ComDzhyunProtoDzhIndicate_Indicate_descriptor_, bytes, registry);
}

ComDzhyunProtoDzhIndicate_Indicate *ComDzhyunProtoDzhIndicate_Indicate_parseFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhIndicate_Indicate_initialize();
  return (ComDzhyunProtoDzhIndicate_Indicate *)CGPParseFromInputStream(ComDzhyunProtoDzhIndicate_Indicate_descriptor_, input, registry);
}
ComDzhyunProtoDzhIndicate_Indicate *ComDzhyunProtoDzhIndicate_Indicate_parseDelimitedFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhIndicate_Indicate_initialize();
  return (ComDzhyunProtoDzhIndicate_Indicate *)CGPParseDelimitedFromInputStream(ComDzhyunProtoDzhIndicate_Indicate_descriptor_, input, registry);
}

@implementation ComDzhyunProtoDzhIndicate_Indicate_Builder

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return [ComDzhyunProtoDzhIndicate_Indicate getDescriptor];
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhIndicate_Indicate_Builder)
J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhIndicate_IndicateOrBuilder)

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhIndicate_Indicate_Builder_getDescriptor() {
  ComDzhyunProtoDzhIndicate_Indicate_initialize();
  return ComDzhyunProtoDzhIndicate_Indicate_descriptor_;
}

J2OBJC_INITIALIZED_DEFN(ComDzhyunProtoDzhIndicate_IndicatorQueryOutput);

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_descriptor_;

@implementation ComDzhyunProtoDzhIndicate_IndicatorQueryOutput

typedef struct ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_Storage {
  uint32_t hasBits[0];
  CGPRepeatedField indicates_;
} ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_Storage;

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_descriptor_;
}

+ (void)initialize {
  if (self == [ComDzhyunProtoDzhIndicate_IndicatorQueryOutput class]) {
    static CGPFieldData fields[] = {
      {
        .name = "Indicates",
        .javaName = "Indicates",
        .number = 1,
        .flags = CGPFieldFlagRepeated,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_MESSAGE,
        .defaultValue.valueId = nil,
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_Storage, indicates_),
        .className = "ComDzhyunProtoDzhIndicate_Indicate",
        .containingType = "ComDzhyunProtoDzhIndicate_IndicatorQueryOutput",
        .optionsData = NULL,
      },
    };
    CGPInitDescriptor(&ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_descriptor_, self, [ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_Builder class], 0, sizeof(ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_Storage), 1, fields);
    J2OBJC_SET_INITIALIZED(ComDzhyunProtoDzhIndicate_IndicatorQueryOutput)
  }
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhIndicate_IndicatorQueryOutput)

ComDzhyunProtoDzhIndicate_IndicatorQueryOutput *ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_getDefaultInstance() {
  ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_initialize();
  return (ComDzhyunProtoDzhIndicate_IndicatorQueryOutput *)[CGPNewMessage(ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_descriptor_) autorelease];
}

ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_Builder *ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_newBuilder() {
  ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_initialize();
  return (ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_Builder *)[CGPNewBuilder(ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_descriptor_) autorelease];
}

ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_Builder *ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_newBuilderWithComDzhyunProtoDzhIndicate_IndicatorQueryOutput_(ComDzhyunProtoDzhIndicate_IndicatorQueryOutput *message) {
  ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_initialize();
  return (ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_Builder *)CGPBuilderFromPrototype(ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_descriptor_, message);
}

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_getDescriptor() {
  ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_initialize();
  return ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_descriptor_;
}

ComDzhyunProtoDzhIndicate_IndicatorQueryOutput *ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_parseFromWithByteArray_withComGoogleProtobufExtensionRegistryLite_(IOSByteArray *bytes, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_initialize();
  return (ComDzhyunProtoDzhIndicate_IndicatorQueryOutput *)CGPParseFromByteArray(ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_descriptor_, bytes, registry);
}

ComDzhyunProtoDzhIndicate_IndicatorQueryOutput *ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_parseFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_initialize();
  return (ComDzhyunProtoDzhIndicate_IndicatorQueryOutput *)CGPParseFromInputStream(ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_descriptor_, input, registry);
}
ComDzhyunProtoDzhIndicate_IndicatorQueryOutput *ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_parseDelimitedFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_initialize();
  return (ComDzhyunProtoDzhIndicate_IndicatorQueryOutput *)CGPParseDelimitedFromInputStream(ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_descriptor_, input, registry);
}

@implementation ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_Builder

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return [ComDzhyunProtoDzhIndicate_IndicatorQueryOutput getDescriptor];
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_Builder)
J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhIndicate_IndicatorQueryOutputOrBuilder)

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_Builder_getDescriptor() {
  ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_initialize();
  return ComDzhyunProtoDzhIndicate_IndicatorQueryOutput_descriptor_;
}
