// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dzhselfstock.proto

#import "J2ObjC_source.h"
#import "com/dzhyun/proto/Dzhselfstock.h"
#import "com/google/protobuf/Descriptors_PackagePrivate.h"
#import "com/google/protobuf/ExtensionRegistry.h"
#import "com/google/protobuf/GeneratedMessage_PackagePrivate.h"
#import "com/google/protobuf/RepeatedField.h"
#import "java/lang/IllegalArgumentException.h"

#pragma GCC diagnostic ignored "-Wprotocol"
#pragma clang diagnostic ignored "-Wprotocol"
#pragma GCC diagnostic ignored "-Wincomplete-implementation"
#pragma clang diagnostic ignored "-Wincomplete-implementation"

@implementation ComDzhyunProtoDzhselfstock

+ (void)registerAllExtensionsWithComGoogleProtobufExtensionRegistry:(ComGoogleProtobufExtensionRegistry *)extensionRegistry {
  ComDzhyunProtoDzhselfstock_registerAllExtensionsWithComGoogleProtobufExtensionRegistry_(extensionRegistry);
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhselfstock)

void ComDzhyunProtoDzhselfstock_registerAllExtensionsWithComGoogleProtobufExtensionRegistry_(ComGoogleProtobufExtensionRegistry *extensionRegistry) {
}

J2OBJC_INITIALIZED_DEFN(ComDzhyunProtoDzhselfstock_SelfStock);

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhselfstock_SelfStock_descriptor_;

@implementation ComDzhyunProtoDzhselfstock_SelfStock

typedef struct ComDzhyunProtoDzhselfstock_SelfStock_Storage {
  uint32_t hasBits[1];
  NSString *stockCode_;
  long long int addTime_;
  int op_;
} ComDzhyunProtoDzhselfstock_SelfStock_Storage;

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return ComDzhyunProtoDzhselfstock_SelfStock_descriptor_;
}

+ (void)initialize {
  if (self == [ComDzhyunProtoDzhselfstock_SelfStock class]) {
    static CGPFieldData fields[] = {
      {
        .name = "stock_code",
        .javaName = "StockCode",
        .number = 1,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_STRING,
        .defaultValue.valueId = @"",
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhselfstock_SelfStock_Storage, stockCode_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhselfstock_SelfStock",
        .optionsData = NULL,
      },
      {
        .name = "add_time",
        .javaName = "AddTime",
        .number = 2,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 1,
        .offset = offsetof(ComDzhyunProtoDzhselfstock_SelfStock_Storage, addTime_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhselfstock_SelfStock",
        .optionsData = NULL,
      },
      {
        .name = "op",
        .javaName = "Op",
        .number = 3,
        .flags = 0,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT32,
        .defaultValue.valueInt = 0,
        .hasBitIndex = 2,
        .offset = offsetof(ComDzhyunProtoDzhselfstock_SelfStock_Storage, op_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhselfstock_SelfStock",
        .optionsData = NULL,
      },
    };
    CGPInitDescriptor(&ComDzhyunProtoDzhselfstock_SelfStock_descriptor_, self, [ComDzhyunProtoDzhselfstock_SelfStock_Builder class], 0, sizeof(ComDzhyunProtoDzhselfstock_SelfStock_Storage), 3, fields);
    J2OBJC_SET_INITIALIZED(ComDzhyunProtoDzhselfstock_SelfStock)
  }
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhselfstock_SelfStock)

ComDzhyunProtoDzhselfstock_SelfStock *ComDzhyunProtoDzhselfstock_SelfStock_getDefaultInstance() {
  ComDzhyunProtoDzhselfstock_SelfStock_initialize();
  return (ComDzhyunProtoDzhselfstock_SelfStock *)[CGPNewMessage(ComDzhyunProtoDzhselfstock_SelfStock_descriptor_) autorelease];
}

ComDzhyunProtoDzhselfstock_SelfStock_Builder *ComDzhyunProtoDzhselfstock_SelfStock_newBuilder() {
  ComDzhyunProtoDzhselfstock_SelfStock_initialize();
  return (ComDzhyunProtoDzhselfstock_SelfStock_Builder *)[CGPNewBuilder(ComDzhyunProtoDzhselfstock_SelfStock_descriptor_) autorelease];
}

ComDzhyunProtoDzhselfstock_SelfStock_Builder *ComDzhyunProtoDzhselfstock_SelfStock_newBuilderWithComDzhyunProtoDzhselfstock_SelfStock_(ComDzhyunProtoDzhselfstock_SelfStock *message) {
  ComDzhyunProtoDzhselfstock_SelfStock_initialize();
  return (ComDzhyunProtoDzhselfstock_SelfStock_Builder *)CGPBuilderFromPrototype(ComDzhyunProtoDzhselfstock_SelfStock_descriptor_, message);
}

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhselfstock_SelfStock_getDescriptor() {
  ComDzhyunProtoDzhselfstock_SelfStock_initialize();
  return ComDzhyunProtoDzhselfstock_SelfStock_descriptor_;
}

ComDzhyunProtoDzhselfstock_SelfStock *ComDzhyunProtoDzhselfstock_SelfStock_parseFromWithByteArray_withComGoogleProtobufExtensionRegistryLite_(IOSByteArray *bytes, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhselfstock_SelfStock_initialize();
  return (ComDzhyunProtoDzhselfstock_SelfStock *)CGPParseFromByteArray(ComDzhyunProtoDzhselfstock_SelfStock_descriptor_, bytes, registry);
}

ComDzhyunProtoDzhselfstock_SelfStock *ComDzhyunProtoDzhselfstock_SelfStock_parseFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhselfstock_SelfStock_initialize();
  return (ComDzhyunProtoDzhselfstock_SelfStock *)CGPParseFromInputStream(ComDzhyunProtoDzhselfstock_SelfStock_descriptor_, input, registry);
}
ComDzhyunProtoDzhselfstock_SelfStock *ComDzhyunProtoDzhselfstock_SelfStock_parseDelimitedFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhselfstock_SelfStock_initialize();
  return (ComDzhyunProtoDzhselfstock_SelfStock *)CGPParseDelimitedFromInputStream(ComDzhyunProtoDzhselfstock_SelfStock_descriptor_, input, registry);
}

@implementation ComDzhyunProtoDzhselfstock_SelfStock_Builder

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return [ComDzhyunProtoDzhselfstock_SelfStock getDescriptor];
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhselfstock_SelfStock_Builder)
J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhselfstock_SelfStockOrBuilder)

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhselfstock_SelfStock_Builder_getDescriptor() {
  ComDzhyunProtoDzhselfstock_SelfStock_initialize();
  return ComDzhyunProtoDzhselfstock_SelfStock_descriptor_;
}

J2OBJC_INITIALIZED_DEFN(ComDzhyunProtoDzhselfstock_FullSelfStock);

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhselfstock_FullSelfStock_descriptor_;

@implementation ComDzhyunProtoDzhselfstock_FullSelfStock

typedef struct ComDzhyunProtoDzhselfstock_FullSelfStock_Storage {
  uint32_t hasBits[1];
  CGPRepeatedField codes_;
  long long int position_;
} ComDzhyunProtoDzhselfstock_FullSelfStock_Storage;

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return ComDzhyunProtoDzhselfstock_FullSelfStock_descriptor_;
}

+ (void)initialize {
  if (self == [ComDzhyunProtoDzhselfstock_FullSelfStock class]) {
    static CGPFieldData fields[] = {
      {
        .name = "codes",
        .javaName = "Codes",
        .number = 1,
        .flags = CGPFieldFlagRepeated,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_MESSAGE,
        .defaultValue.valueId = nil,
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhselfstock_FullSelfStock_Storage, codes_),
        .className = "ComDzhyunProtoDzhselfstock_SelfStock",
        .containingType = "ComDzhyunProtoDzhselfstock_FullSelfStock",
        .optionsData = NULL,
      },
      {
        .name = "position",
        .javaName = "Position",
        .number = 2,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhselfstock_FullSelfStock_Storage, position_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhselfstock_FullSelfStock",
        .optionsData = NULL,
      },
    };
    CGPInitDescriptor(&ComDzhyunProtoDzhselfstock_FullSelfStock_descriptor_, self, [ComDzhyunProtoDzhselfstock_FullSelfStock_Builder class], 0, sizeof(ComDzhyunProtoDzhselfstock_FullSelfStock_Storage), 2, fields);
    J2OBJC_SET_INITIALIZED(ComDzhyunProtoDzhselfstock_FullSelfStock)
  }
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhselfstock_FullSelfStock)

ComDzhyunProtoDzhselfstock_FullSelfStock *ComDzhyunProtoDzhselfstock_FullSelfStock_getDefaultInstance() {
  ComDzhyunProtoDzhselfstock_FullSelfStock_initialize();
  return (ComDzhyunProtoDzhselfstock_FullSelfStock *)[CGPNewMessage(ComDzhyunProtoDzhselfstock_FullSelfStock_descriptor_) autorelease];
}

ComDzhyunProtoDzhselfstock_FullSelfStock_Builder *ComDzhyunProtoDzhselfstock_FullSelfStock_newBuilder() {
  ComDzhyunProtoDzhselfstock_FullSelfStock_initialize();
  return (ComDzhyunProtoDzhselfstock_FullSelfStock_Builder *)[CGPNewBuilder(ComDzhyunProtoDzhselfstock_FullSelfStock_descriptor_) autorelease];
}

ComDzhyunProtoDzhselfstock_FullSelfStock_Builder *ComDzhyunProtoDzhselfstock_FullSelfStock_newBuilderWithComDzhyunProtoDzhselfstock_FullSelfStock_(ComDzhyunProtoDzhselfstock_FullSelfStock *message) {
  ComDzhyunProtoDzhselfstock_FullSelfStock_initialize();
  return (ComDzhyunProtoDzhselfstock_FullSelfStock_Builder *)CGPBuilderFromPrototype(ComDzhyunProtoDzhselfstock_FullSelfStock_descriptor_, message);
}

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhselfstock_FullSelfStock_getDescriptor() {
  ComDzhyunProtoDzhselfstock_FullSelfStock_initialize();
  return ComDzhyunProtoDzhselfstock_FullSelfStock_descriptor_;
}

ComDzhyunProtoDzhselfstock_FullSelfStock *ComDzhyunProtoDzhselfstock_FullSelfStock_parseFromWithByteArray_withComGoogleProtobufExtensionRegistryLite_(IOSByteArray *bytes, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhselfstock_FullSelfStock_initialize();
  return (ComDzhyunProtoDzhselfstock_FullSelfStock *)CGPParseFromByteArray(ComDzhyunProtoDzhselfstock_FullSelfStock_descriptor_, bytes, registry);
}

ComDzhyunProtoDzhselfstock_FullSelfStock *ComDzhyunProtoDzhselfstock_FullSelfStock_parseFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhselfstock_FullSelfStock_initialize();
  return (ComDzhyunProtoDzhselfstock_FullSelfStock *)CGPParseFromInputStream(ComDzhyunProtoDzhselfstock_FullSelfStock_descriptor_, input, registry);
}
ComDzhyunProtoDzhselfstock_FullSelfStock *ComDzhyunProtoDzhselfstock_FullSelfStock_parseDelimitedFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhselfstock_FullSelfStock_initialize();
  return (ComDzhyunProtoDzhselfstock_FullSelfStock *)CGPParseDelimitedFromInputStream(ComDzhyunProtoDzhselfstock_FullSelfStock_descriptor_, input, registry);
}

@implementation ComDzhyunProtoDzhselfstock_FullSelfStock_Builder

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return [ComDzhyunProtoDzhselfstock_FullSelfStock getDescriptor];
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhselfstock_FullSelfStock_Builder)
J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhselfstock_FullSelfStockOrBuilder)

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhselfstock_FullSelfStock_Builder_getDescriptor() {
  ComDzhyunProtoDzhselfstock_FullSelfStock_initialize();
  return ComDzhyunProtoDzhselfstock_FullSelfStock_descriptor_;
}

J2OBJC_INITIALIZED_DEFN(ComDzhyunProtoDzhselfstock_SelfStockGetOutput);

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhselfstock_SelfStockGetOutput_descriptor_;

@implementation ComDzhyunProtoDzhselfstock_SelfStockGetOutput

typedef struct ComDzhyunProtoDzhselfstock_SelfStockGetOutput_Storage {
  uint32_t hasBits[1];
  long long int uid_;
  CGPRepeatedField codes_;
  int type_;
} ComDzhyunProtoDzhselfstock_SelfStockGetOutput_Storage;

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return ComDzhyunProtoDzhselfstock_SelfStockGetOutput_descriptor_;
}

+ (void)initialize {
  if (self == [ComDzhyunProtoDzhselfstock_SelfStockGetOutput class]) {
    static CGPFieldData fields[] = {
      {
        .name = "uid",
        .javaName = "Uid",
        .number = 1,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhselfstock_SelfStockGetOutput_Storage, uid_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhselfstock_SelfStockGetOutput",
        .optionsData = NULL,
      },
      {
        .name = "codes",
        .javaName = "Codes",
        .number = 2,
        .flags = CGPFieldFlagRepeated,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_MESSAGE,
        .defaultValue.valueId = nil,
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhselfstock_SelfStockGetOutput_Storage, codes_),
        .className = "ComDzhyunProtoDzhselfstock_SelfStock",
        .containingType = "ComDzhyunProtoDzhselfstock_SelfStockGetOutput",
        .optionsData = NULL,
      },
      {
        .name = "type",
        .javaName = "Type",
        .number = 3,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT32,
        .defaultValue.valueInt = 0,
        .hasBitIndex = 1,
        .offset = offsetof(ComDzhyunProtoDzhselfstock_SelfStockGetOutput_Storage, type_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhselfstock_SelfStockGetOutput",
        .optionsData = NULL,
      },
    };
    CGPInitDescriptor(&ComDzhyunProtoDzhselfstock_SelfStockGetOutput_descriptor_, self, [ComDzhyunProtoDzhselfstock_SelfStockGetOutput_Builder class], 0, sizeof(ComDzhyunProtoDzhselfstock_SelfStockGetOutput_Storage), 3, fields);
    J2OBJC_SET_INITIALIZED(ComDzhyunProtoDzhselfstock_SelfStockGetOutput)
  }
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhselfstock_SelfStockGetOutput)

ComDzhyunProtoDzhselfstock_SelfStockGetOutput *ComDzhyunProtoDzhselfstock_SelfStockGetOutput_getDefaultInstance() {
  ComDzhyunProtoDzhselfstock_SelfStockGetOutput_initialize();
  return (ComDzhyunProtoDzhselfstock_SelfStockGetOutput *)[CGPNewMessage(ComDzhyunProtoDzhselfstock_SelfStockGetOutput_descriptor_) autorelease];
}

ComDzhyunProtoDzhselfstock_SelfStockGetOutput_Builder *ComDzhyunProtoDzhselfstock_SelfStockGetOutput_newBuilder() {
  ComDzhyunProtoDzhselfstock_SelfStockGetOutput_initialize();
  return (ComDzhyunProtoDzhselfstock_SelfStockGetOutput_Builder *)[CGPNewBuilder(ComDzhyunProtoDzhselfstock_SelfStockGetOutput_descriptor_) autorelease];
}

ComDzhyunProtoDzhselfstock_SelfStockGetOutput_Builder *ComDzhyunProtoDzhselfstock_SelfStockGetOutput_newBuilderWithComDzhyunProtoDzhselfstock_SelfStockGetOutput_(ComDzhyunProtoDzhselfstock_SelfStockGetOutput *message) {
  ComDzhyunProtoDzhselfstock_SelfStockGetOutput_initialize();
  return (ComDzhyunProtoDzhselfstock_SelfStockGetOutput_Builder *)CGPBuilderFromPrototype(ComDzhyunProtoDzhselfstock_SelfStockGetOutput_descriptor_, message);
}

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhselfstock_SelfStockGetOutput_getDescriptor() {
  ComDzhyunProtoDzhselfstock_SelfStockGetOutput_initialize();
  return ComDzhyunProtoDzhselfstock_SelfStockGetOutput_descriptor_;
}

ComDzhyunProtoDzhselfstock_SelfStockGetOutput *ComDzhyunProtoDzhselfstock_SelfStockGetOutput_parseFromWithByteArray_withComGoogleProtobufExtensionRegistryLite_(IOSByteArray *bytes, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhselfstock_SelfStockGetOutput_initialize();
  return (ComDzhyunProtoDzhselfstock_SelfStockGetOutput *)CGPParseFromByteArray(ComDzhyunProtoDzhselfstock_SelfStockGetOutput_descriptor_, bytes, registry);
}

ComDzhyunProtoDzhselfstock_SelfStockGetOutput *ComDzhyunProtoDzhselfstock_SelfStockGetOutput_parseFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhselfstock_SelfStockGetOutput_initialize();
  return (ComDzhyunProtoDzhselfstock_SelfStockGetOutput *)CGPParseFromInputStream(ComDzhyunProtoDzhselfstock_SelfStockGetOutput_descriptor_, input, registry);
}
ComDzhyunProtoDzhselfstock_SelfStockGetOutput *ComDzhyunProtoDzhselfstock_SelfStockGetOutput_parseDelimitedFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhselfstock_SelfStockGetOutput_initialize();
  return (ComDzhyunProtoDzhselfstock_SelfStockGetOutput *)CGPParseDelimitedFromInputStream(ComDzhyunProtoDzhselfstock_SelfStockGetOutput_descriptor_, input, registry);
}

@implementation ComDzhyunProtoDzhselfstock_SelfStockGetOutput_Builder

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return [ComDzhyunProtoDzhselfstock_SelfStockGetOutput getDescriptor];
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhselfstock_SelfStockGetOutput_Builder)
J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhselfstock_SelfStockGetOutputOrBuilder)

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhselfstock_SelfStockGetOutput_Builder_getDescriptor() {
  ComDzhyunProtoDzhselfstock_SelfStockGetOutput_initialize();
  return ComDzhyunProtoDzhselfstock_SelfStockGetOutput_descriptor_;
}

J2OBJC_INITIALIZED_DEFN(ComDzhyunProtoDzhselfstock_SelfStockPutOutput);

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhselfstock_SelfStockPutOutput_descriptor_;

@implementation ComDzhyunProtoDzhselfstock_SelfStockPutOutput

typedef struct ComDzhyunProtoDzhselfstock_SelfStockPutOutput_Storage {
  uint32_t hasBits[1];
  long long int uid_;
  NSString *status_;
} ComDzhyunProtoDzhselfstock_SelfStockPutOutput_Storage;

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return ComDzhyunProtoDzhselfstock_SelfStockPutOutput_descriptor_;
}

+ (void)initialize {
  if (self == [ComDzhyunProtoDzhselfstock_SelfStockPutOutput class]) {
    static CGPFieldData fields[] = {
      {
        .name = "uid",
        .javaName = "Uid",
        .number = 1,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhselfstock_SelfStockPutOutput_Storage, uid_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhselfstock_SelfStockPutOutput",
        .optionsData = NULL,
      },
      {
        .name = "status",
        .javaName = "Status",
        .number = 2,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_STRING,
        .defaultValue.valueId = @"",
        .hasBitIndex = 1,
        .offset = offsetof(ComDzhyunProtoDzhselfstock_SelfStockPutOutput_Storage, status_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhselfstock_SelfStockPutOutput",
        .optionsData = NULL,
      },
    };
    CGPInitDescriptor(&ComDzhyunProtoDzhselfstock_SelfStockPutOutput_descriptor_, self, [ComDzhyunProtoDzhselfstock_SelfStockPutOutput_Builder class], 0, sizeof(ComDzhyunProtoDzhselfstock_SelfStockPutOutput_Storage), 2, fields);
    J2OBJC_SET_INITIALIZED(ComDzhyunProtoDzhselfstock_SelfStockPutOutput)
  }
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhselfstock_SelfStockPutOutput)

ComDzhyunProtoDzhselfstock_SelfStockPutOutput *ComDzhyunProtoDzhselfstock_SelfStockPutOutput_getDefaultInstance() {
  ComDzhyunProtoDzhselfstock_SelfStockPutOutput_initialize();
  return (ComDzhyunProtoDzhselfstock_SelfStockPutOutput *)[CGPNewMessage(ComDzhyunProtoDzhselfstock_SelfStockPutOutput_descriptor_) autorelease];
}

ComDzhyunProtoDzhselfstock_SelfStockPutOutput_Builder *ComDzhyunProtoDzhselfstock_SelfStockPutOutput_newBuilder() {
  ComDzhyunProtoDzhselfstock_SelfStockPutOutput_initialize();
  return (ComDzhyunProtoDzhselfstock_SelfStockPutOutput_Builder *)[CGPNewBuilder(ComDzhyunProtoDzhselfstock_SelfStockPutOutput_descriptor_) autorelease];
}

ComDzhyunProtoDzhselfstock_SelfStockPutOutput_Builder *ComDzhyunProtoDzhselfstock_SelfStockPutOutput_newBuilderWithComDzhyunProtoDzhselfstock_SelfStockPutOutput_(ComDzhyunProtoDzhselfstock_SelfStockPutOutput *message) {
  ComDzhyunProtoDzhselfstock_SelfStockPutOutput_initialize();
  return (ComDzhyunProtoDzhselfstock_SelfStockPutOutput_Builder *)CGPBuilderFromPrototype(ComDzhyunProtoDzhselfstock_SelfStockPutOutput_descriptor_, message);
}

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhselfstock_SelfStockPutOutput_getDescriptor() {
  ComDzhyunProtoDzhselfstock_SelfStockPutOutput_initialize();
  return ComDzhyunProtoDzhselfstock_SelfStockPutOutput_descriptor_;
}

ComDzhyunProtoDzhselfstock_SelfStockPutOutput *ComDzhyunProtoDzhselfstock_SelfStockPutOutput_parseFromWithByteArray_withComGoogleProtobufExtensionRegistryLite_(IOSByteArray *bytes, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhselfstock_SelfStockPutOutput_initialize();
  return (ComDzhyunProtoDzhselfstock_SelfStockPutOutput *)CGPParseFromByteArray(ComDzhyunProtoDzhselfstock_SelfStockPutOutput_descriptor_, bytes, registry);
}

ComDzhyunProtoDzhselfstock_SelfStockPutOutput *ComDzhyunProtoDzhselfstock_SelfStockPutOutput_parseFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhselfstock_SelfStockPutOutput_initialize();
  return (ComDzhyunProtoDzhselfstock_SelfStockPutOutput *)CGPParseFromInputStream(ComDzhyunProtoDzhselfstock_SelfStockPutOutput_descriptor_, input, registry);
}
ComDzhyunProtoDzhselfstock_SelfStockPutOutput *ComDzhyunProtoDzhselfstock_SelfStockPutOutput_parseDelimitedFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhselfstock_SelfStockPutOutput_initialize();
  return (ComDzhyunProtoDzhselfstock_SelfStockPutOutput *)CGPParseDelimitedFromInputStream(ComDzhyunProtoDzhselfstock_SelfStockPutOutput_descriptor_, input, registry);
}

@implementation ComDzhyunProtoDzhselfstock_SelfStockPutOutput_Builder

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return [ComDzhyunProtoDzhselfstock_SelfStockPutOutput getDescriptor];
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhselfstock_SelfStockPutOutput_Builder)
J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhselfstock_SelfStockPutOutputOrBuilder)

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhselfstock_SelfStockPutOutput_Builder_getDescriptor() {
  ComDzhyunProtoDzhselfstock_SelfStockPutOutput_initialize();
  return ComDzhyunProtoDzhselfstock_SelfStockPutOutput_descriptor_;
}
