// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dzhyun.static.proto

#import "J2ObjC_header.h"
#import "com/google/protobuf/GeneratedMessage.h"
#import "com/google/protobuf/MessageOrBuilder.h"
#import "com/google/protobuf/ProtocolMessageEnum.h"
#import "java/lang/Enum.h"

@class ComDzhyunProtoDzhyunStatic_Static;
@class ComDzhyunProtoDzhyunStatic_StaticTable_Builder;
@class ComDzhyunProtoDzhyunStatic_Static_Builder;
@class ComDzhyunProtoDzhyunStatic_TradeTime;
@class ComDzhyunProtoDzhyunStatic_TradeTime_Builder;
@class ComGoogleProtobufDescriptors_Descriptor;
@class ComGoogleProtobufExtensionRegistry;
@protocol JavaLangIterable;
@protocol JavaUtilList;

@interface ComDzhyunProtoDzhyunStatic : NSObject

+ (void)registerAllExtensionsWithComGoogleProtobufExtensionRegistry:(ComGoogleProtobufExtensionRegistry *)extensionRegistry;

@end

FOUNDATION_EXPORT void ComDzhyunProtoDzhyunStatic_registerAllExtensionsWithComGoogleProtobufExtensionRegistry_(ComGoogleProtobufExtensionRegistry *extensionRegistry);

J2OBJC_EMPTY_STATIC_INIT(ComDzhyunProtoDzhyunStatic)

J2OBJC_TYPE_LITERAL_HEADER(ComDzhyunProtoDzhyunStatic)

@protocol ComDzhyunProtoDzhyunStatic_TradeTimeOrBuilder < ComGoogleProtobufMessageOrBuilder >

- (BOOL)hasStartTime;
- (long long int)getStartTime;

- (BOOL)hasEndTime;
- (long long int)getEndTime;

@end

J2OBJC_EMPTY_STATIC_INIT(ComDzhyunProtoDzhyunStatic_TradeTimeOrBuilder)

J2OBJC_TYPE_LITERAL_HEADER(ComDzhyunProtoDzhyunStatic_TradeTimeOrBuilder)

@interface ComDzhyunProtoDzhyunStatic_TradeTime : ComGoogleProtobufGeneratedMessage<ComDzhyunProtoDzhyunStatic_TradeTimeOrBuilder>

+ (ComDzhyunProtoDzhyunStatic_TradeTime *)getDefaultInstance;
- (ComDzhyunProtoDzhyunStatic_TradeTime *)getDefaultInstanceForType;
+ (ComDzhyunProtoDzhyunStatic_TradeTime_Builder *)newBuilder OBJC_METHOD_FAMILY_NONE;
- (ComDzhyunProtoDzhyunStatic_TradeTime_Builder *)newBuilderForType OBJC_METHOD_FAMILY_NONE;
- (ComDzhyunProtoDzhyunStatic_TradeTime_Builder *)toBuilder;
+ (ComDzhyunProtoDzhyunStatic_TradeTime_Builder *)newBuilderWithComDzhyunProtoDzhyunStatic_TradeTime:(ComDzhyunProtoDzhyunStatic_TradeTime *)message OBJC_METHOD_FAMILY_NONE;
+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor;
+ (ComDzhyunProtoDzhyunStatic_TradeTime *)parseFromWithByteArray:(IOSByteArray *)bytes;
+ (ComDzhyunProtoDzhyunStatic_TradeTime *)parseFromWithByteArray:(IOSByteArray *)bytes withComGoogleProtobufExtensionRegistryLite:(ComGoogleProtobufExtensionRegistryLite *)registry;
+ (ComDzhyunProtoDzhyunStatic_TradeTime *)parseFromNSData:(NSData *)data;
+ (ComDzhyunProtoDzhyunStatic_TradeTime *)parseFromNSData:(NSData *)data registry:(ComGoogleProtobufExtensionRegistryLite *)registry;
+ (ComDzhyunProtoDzhyunStatic_TradeTime *)parseFromWithJavaIoInputStream:(JavaIoInputStream *)input;
+ (ComDzhyunProtoDzhyunStatic_TradeTime *)parseFromWithJavaIoInputStream:(JavaIoInputStream *)bytes withComGoogleProtobufExtensionRegistryLite:(ComGoogleProtobufExtensionRegistryLite *)registry;
+ (ComDzhyunProtoDzhyunStatic_TradeTime *)parseDelimitedFromWithJavaIoInputStream:(JavaIoInputStream *)input;
+ (ComDzhyunProtoDzhyunStatic_TradeTime *)parseDelimitedFromWithJavaIoInputStream:(JavaIoInputStream *)bytes withComGoogleProtobufExtensionRegistryLite:(ComGoogleProtobufExtensionRegistryLite *)registry;

#define ComDzhyunProtoDzhyunStatic_TradeTime_STARTTIME_FIELD_NUMBER 1
#define ComDzhyunProtoDzhyunStatic_TradeTime_ENDTIME_FIELD_NUMBER 2

@end

FOUNDATION_EXPORT ComDzhyunProtoDzhyunStatic_TradeTime *ComDzhyunProtoDzhyunStatic_TradeTime_getDefaultInstance();
FOUNDATION_EXPORT ComDzhyunProtoDzhyunStatic_TradeTime_Builder *ComDzhyunProtoDzhyunStatic_TradeTime_newBuilder();
FOUNDATION_EXPORT ComDzhyunProtoDzhyunStatic_TradeTime_Builder *ComDzhyunProtoDzhyunStatic_TradeTime_newBuilderWithComDzhyunProtoDzhyunStatic_TradeTime_(ComDzhyunProtoDzhyunStatic_TradeTime *message);
FOUNDATION_EXPORT ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunStatic_TradeTime_getDescriptor();
FOUNDATION_EXPORT ComDzhyunProtoDzhyunStatic_TradeTime *ComDzhyunProtoDzhyunStatic_TradeTime_parseFromWithByteArray_withComGoogleProtobufExtensionRegistryLite_(IOSByteArray *bytes, ComGoogleProtobufExtensionRegistryLite *registry);
CGP_ALWAYS_INLINE inline ComDzhyunProtoDzhyunStatic_TradeTime *ComDzhyunProtoDzhyunStatic_TradeTime_parseFromWithByteArray_(IOSByteArray *bytes) {
  return ComDzhyunProtoDzhyunStatic_TradeTime_parseFromWithByteArray_withComGoogleProtobufExtensionRegistryLite_(bytes, nil);
}
FOUNDATION_EXPORT ComDzhyunProtoDzhyunStatic_TradeTime *ComDzhyunProtoDzhyunStatic_TradeTime_parseFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry);
CGP_ALWAYS_INLINE inline ComDzhyunProtoDzhyunStatic_TradeTime *ComDzhyunProtoDzhyunStatic_TradeTime_parseFromWithJavaIoInputStream_(JavaIoInputStream *input) {
  return ComDzhyunProtoDzhyunStatic_TradeTime_parseFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(input, nil);
}
FOUNDATION_EXPORT ComDzhyunProtoDzhyunStatic_TradeTime *ComDzhyunProtoDzhyunStatic_TradeTime_parseDelimitedFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry);
CGP_ALWAYS_INLINE inline ComDzhyunProtoDzhyunStatic_TradeTime *ComDzhyunProtoDzhyunStatic_TradeTime_parseDelimitedFromWithJavaIoInputStream_(JavaIoInputStream *input) {
  return ComDzhyunProtoDzhyunStatic_TradeTime_parseDelimitedFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(input, nil);
}

J2OBJC_STATIC_INIT(ComDzhyunProtoDzhyunStatic_TradeTime)

J2OBJC_TYPE_LITERAL_HEADER(ComDzhyunProtoDzhyunStatic_TradeTime)

FOUNDATION_EXPORT ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunStatic_TradeTime_descriptor_;

@interface ComDzhyunProtoDzhyunStatic_TradeTime_Builder : ComGoogleProtobufGeneratedMessage_Builder<ComDzhyunProtoDzhyunStatic_TradeTimeOrBuilder>

- (ComDzhyunProtoDzhyunStatic_TradeTime *)getDefaultInstanceForType;
- (ComDzhyunProtoDzhyunStatic_TradeTime_Builder *)mergeFromWithComDzhyunProtoDzhyunStatic_TradeTime:(ComDzhyunProtoDzhyunStatic_TradeTime *)message;
- (ComDzhyunProtoDzhyunStatic_TradeTime_Builder *)mergeFromWithComGoogleProtobufMessage:(id<ComGoogleProtobufMessage>)message;
- (ComDzhyunProtoDzhyunStatic_TradeTime *)build;
- (ComDzhyunProtoDzhyunStatic_TradeTime *)buildPartial;
+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor;

- (ComDzhyunProtoDzhyunStatic_TradeTime_Builder *)setStartTimeWithLong:
    (long long int)value;
- (ComDzhyunProtoDzhyunStatic_TradeTime_Builder *)clearStartTime;

- (ComDzhyunProtoDzhyunStatic_TradeTime_Builder *)setEndTimeWithLong:
    (long long int)value;
- (ComDzhyunProtoDzhyunStatic_TradeTime_Builder *)clearEndTime;

@end

FOUNDATION_EXPORT ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunStatic_TradeTime_Builder_getDescriptor();

J2OBJC_EMPTY_STATIC_INIT(ComDzhyunProtoDzhyunStatic_TradeTime_Builder)

J2OBJC_TYPE_LITERAL_HEADER(ComDzhyunProtoDzhyunStatic_TradeTime_Builder)

@protocol ComDzhyunProtoDzhyunStatic_StaticOrBuilder < ComGoogleProtobufMessageOrBuilder >

- (BOOL)hasObj;
- (NSString *)getObj;

- (BOOL)hasZhongWenJianCheng;
- (NSString *)getZhongWenJianCheng;

- (BOOL)hasLeiXing;
- (long long int)getLeiXing;

- (BOOL)hasZiLeiXing;
- (long long int)getZiLeiXing;

- (BOOL)hasXiaoShuWei;
- (long long int)getXiaoShuWei;

- (BOOL)hasMeiShouGuShu;
- (long long int)getMeiShouGuShu;

- (BOOL)hasLiuTongGuBen;
- (long long int)getLiuTongGuBen;

- (BOOL)hasZongGuBen;
- (long long int)getZongGuBen;

- (BOOL)hasZuoShou;
- (long long int)getZuoShou;

- (BOOL)hasZhangTing;
- (long long int)getZhangTing;

- (BOOL)hasDieTing;
- (long long int)getDieTing;

- (BOOL)hasTradeTimeNum;
- (long long int)getTradeTimeNum;

- (int)getTradeTimesCount;
- (id<JavaUtilList>)getTradeTimesList;
- (ComDzhyunProtoDzhyunStatic_TradeTime *)getTradeTimesWithInt:(int)index;

@end

J2OBJC_EMPTY_STATIC_INIT(ComDzhyunProtoDzhyunStatic_StaticOrBuilder)

J2OBJC_TYPE_LITERAL_HEADER(ComDzhyunProtoDzhyunStatic_StaticOrBuilder)

@interface ComDzhyunProtoDzhyunStatic_Static : ComGoogleProtobufGeneratedMessage<ComDzhyunProtoDzhyunStatic_StaticOrBuilder>

+ (ComDzhyunProtoDzhyunStatic_Static *)getDefaultInstance;
- (ComDzhyunProtoDzhyunStatic_Static *)getDefaultInstanceForType;
+ (ComDzhyunProtoDzhyunStatic_Static_Builder *)newBuilder OBJC_METHOD_FAMILY_NONE;
- (ComDzhyunProtoDzhyunStatic_Static_Builder *)newBuilderForType OBJC_METHOD_FAMILY_NONE;
- (ComDzhyunProtoDzhyunStatic_Static_Builder *)toBuilder;
+ (ComDzhyunProtoDzhyunStatic_Static_Builder *)newBuilderWithComDzhyunProtoDzhyunStatic_Static:(ComDzhyunProtoDzhyunStatic_Static *)message OBJC_METHOD_FAMILY_NONE;
+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor;
+ (ComDzhyunProtoDzhyunStatic_Static *)parseFromWithByteArray:(IOSByteArray *)bytes;
+ (ComDzhyunProtoDzhyunStatic_Static *)parseFromWithByteArray:(IOSByteArray *)bytes withComGoogleProtobufExtensionRegistryLite:(ComGoogleProtobufExtensionRegistryLite *)registry;
+ (ComDzhyunProtoDzhyunStatic_Static *)parseFromNSData:(NSData *)data;
+ (ComDzhyunProtoDzhyunStatic_Static *)parseFromNSData:(NSData *)data registry:(ComGoogleProtobufExtensionRegistryLite *)registry;
+ (ComDzhyunProtoDzhyunStatic_Static *)parseFromWithJavaIoInputStream:(JavaIoInputStream *)input;
+ (ComDzhyunProtoDzhyunStatic_Static *)parseFromWithJavaIoInputStream:(JavaIoInputStream *)bytes withComGoogleProtobufExtensionRegistryLite:(ComGoogleProtobufExtensionRegistryLite *)registry;
+ (ComDzhyunProtoDzhyunStatic_Static *)parseDelimitedFromWithJavaIoInputStream:(JavaIoInputStream *)input;
+ (ComDzhyunProtoDzhyunStatic_Static *)parseDelimitedFromWithJavaIoInputStream:(JavaIoInputStream *)bytes withComGoogleProtobufExtensionRegistryLite:(ComGoogleProtobufExtensionRegistryLite *)registry;

#define ComDzhyunProtoDzhyunStatic_Static_OBJ_FIELD_NUMBER 1
#define ComDzhyunProtoDzhyunStatic_Static_ZHONGWENJIANCHENG_FIELD_NUMBER 2
#define ComDzhyunProtoDzhyunStatic_Static_LEIXING_FIELD_NUMBER 3
#define ComDzhyunProtoDzhyunStatic_Static_ZILEIXING_FIELD_NUMBER 4
#define ComDzhyunProtoDzhyunStatic_Static_XIAOSHUWEI_FIELD_NUMBER 5
#define ComDzhyunProtoDzhyunStatic_Static_MEISHOUGUSHU_FIELD_NUMBER 6
#define ComDzhyunProtoDzhyunStatic_Static_LIUTONGGUBEN_FIELD_NUMBER 7
#define ComDzhyunProtoDzhyunStatic_Static_ZONGGUBEN_FIELD_NUMBER 8
#define ComDzhyunProtoDzhyunStatic_Static_ZUOSHOU_FIELD_NUMBER 9
#define ComDzhyunProtoDzhyunStatic_Static_ZHANGTING_FIELD_NUMBER 10
#define ComDzhyunProtoDzhyunStatic_Static_DIETING_FIELD_NUMBER 11
#define ComDzhyunProtoDzhyunStatic_Static_TRADETIMENUM_FIELD_NUMBER 12
#define ComDzhyunProtoDzhyunStatic_Static_TRADETIMES_FIELD_NUMBER 13

@end

FOUNDATION_EXPORT ComDzhyunProtoDzhyunStatic_Static *ComDzhyunProtoDzhyunStatic_Static_getDefaultInstance();
FOUNDATION_EXPORT ComDzhyunProtoDzhyunStatic_Static_Builder *ComDzhyunProtoDzhyunStatic_Static_newBuilder();
FOUNDATION_EXPORT ComDzhyunProtoDzhyunStatic_Static_Builder *ComDzhyunProtoDzhyunStatic_Static_newBuilderWithComDzhyunProtoDzhyunStatic_Static_(ComDzhyunProtoDzhyunStatic_Static *message);
FOUNDATION_EXPORT ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunStatic_Static_getDescriptor();
FOUNDATION_EXPORT ComDzhyunProtoDzhyunStatic_Static *ComDzhyunProtoDzhyunStatic_Static_parseFromWithByteArray_withComGoogleProtobufExtensionRegistryLite_(IOSByteArray *bytes, ComGoogleProtobufExtensionRegistryLite *registry);
CGP_ALWAYS_INLINE inline ComDzhyunProtoDzhyunStatic_Static *ComDzhyunProtoDzhyunStatic_Static_parseFromWithByteArray_(IOSByteArray *bytes) {
  return ComDzhyunProtoDzhyunStatic_Static_parseFromWithByteArray_withComGoogleProtobufExtensionRegistryLite_(bytes, nil);
}
FOUNDATION_EXPORT ComDzhyunProtoDzhyunStatic_Static *ComDzhyunProtoDzhyunStatic_Static_parseFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry);
CGP_ALWAYS_INLINE inline ComDzhyunProtoDzhyunStatic_Static *ComDzhyunProtoDzhyunStatic_Static_parseFromWithJavaIoInputStream_(JavaIoInputStream *input) {
  return ComDzhyunProtoDzhyunStatic_Static_parseFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(input, nil);
}
FOUNDATION_EXPORT ComDzhyunProtoDzhyunStatic_Static *ComDzhyunProtoDzhyunStatic_Static_parseDelimitedFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry);
CGP_ALWAYS_INLINE inline ComDzhyunProtoDzhyunStatic_Static *ComDzhyunProtoDzhyunStatic_Static_parseDelimitedFromWithJavaIoInputStream_(JavaIoInputStream *input) {
  return ComDzhyunProtoDzhyunStatic_Static_parseDelimitedFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(input, nil);
}

J2OBJC_STATIC_INIT(ComDzhyunProtoDzhyunStatic_Static)

J2OBJC_TYPE_LITERAL_HEADER(ComDzhyunProtoDzhyunStatic_Static)

FOUNDATION_EXPORT ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunStatic_Static_descriptor_;

@interface ComDzhyunProtoDzhyunStatic_Static_Builder : ComGoogleProtobufGeneratedMessage_Builder<ComDzhyunProtoDzhyunStatic_StaticOrBuilder>

- (ComDzhyunProtoDzhyunStatic_Static *)getDefaultInstanceForType;
- (ComDzhyunProtoDzhyunStatic_Static_Builder *)mergeFromWithComDzhyunProtoDzhyunStatic_Static:(ComDzhyunProtoDzhyunStatic_Static *)message;
- (ComDzhyunProtoDzhyunStatic_Static_Builder *)mergeFromWithComGoogleProtobufMessage:(id<ComGoogleProtobufMessage>)message;
- (ComDzhyunProtoDzhyunStatic_Static *)build;
- (ComDzhyunProtoDzhyunStatic_Static *)buildPartial;
+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor;

- (ComDzhyunProtoDzhyunStatic_Static_Builder *)setObjWithNSString:
    (NSString *)value;
- (ComDzhyunProtoDzhyunStatic_Static_Builder *)clearObj;

- (ComDzhyunProtoDzhyunStatic_Static_Builder *)setZhongWenJianChengWithNSString:
    (NSString *)value;
- (ComDzhyunProtoDzhyunStatic_Static_Builder *)clearZhongWenJianCheng;

- (ComDzhyunProtoDzhyunStatic_Static_Builder *)setLeiXingWithLong:
    (long long int)value;
- (ComDzhyunProtoDzhyunStatic_Static_Builder *)clearLeiXing;

- (ComDzhyunProtoDzhyunStatic_Static_Builder *)setZiLeiXingWithLong:
    (long long int)value;
- (ComDzhyunProtoDzhyunStatic_Static_Builder *)clearZiLeiXing;

- (ComDzhyunProtoDzhyunStatic_Static_Builder *)setXiaoShuWeiWithLong:
    (long long int)value;
- (ComDzhyunProtoDzhyunStatic_Static_Builder *)clearXiaoShuWei;

- (ComDzhyunProtoDzhyunStatic_Static_Builder *)setMeiShouGuShuWithLong:
    (long long int)value;
- (ComDzhyunProtoDzhyunStatic_Static_Builder *)clearMeiShouGuShu;

- (ComDzhyunProtoDzhyunStatic_Static_Builder *)setLiuTongGuBenWithLong:
    (long long int)value;
- (ComDzhyunProtoDzhyunStatic_Static_Builder *)clearLiuTongGuBen;

- (ComDzhyunProtoDzhyunStatic_Static_Builder *)setZongGuBenWithLong:
    (long long int)value;
- (ComDzhyunProtoDzhyunStatic_Static_Builder *)clearZongGuBen;

- (ComDzhyunProtoDzhyunStatic_Static_Builder *)setZuoShouWithLong:
    (long long int)value;
- (ComDzhyunProtoDzhyunStatic_Static_Builder *)clearZuoShou;

- (ComDzhyunProtoDzhyunStatic_Static_Builder *)setZhangTingWithLong:
    (long long int)value;
- (ComDzhyunProtoDzhyunStatic_Static_Builder *)clearZhangTing;

- (ComDzhyunProtoDzhyunStatic_Static_Builder *)setDieTingWithLong:
    (long long int)value;
- (ComDzhyunProtoDzhyunStatic_Static_Builder *)clearDieTing;

- (ComDzhyunProtoDzhyunStatic_Static_Builder *)setTradeTimeNumWithLong:
    (long long int)value;
- (ComDzhyunProtoDzhyunStatic_Static_Builder *)clearTradeTimeNum;
- (ComDzhyunProtoDzhyunStatic_Static_Builder*)setTradeTimesWithInt:(int)index
    withComDzhyunProtoDzhyunStatic_TradeTime:(ComDzhyunProtoDzhyunStatic_TradeTime *)value;
- (ComDzhyunProtoDzhyunStatic_Static_Builder*)addTradeTimesWithComDzhyunProtoDzhyunStatic_TradeTime:
    (ComDzhyunProtoDzhyunStatic_TradeTime *)value;
- (ComDzhyunProtoDzhyunStatic_Static_Builder*)addAllTradeTimesWithJavaLangIterable:
    (id<JavaLangIterable>)values;
- (ComDzhyunProtoDzhyunStatic_Static_Builder*)clearTradeTimes;
- (ComDzhyunProtoDzhyunStatic_Static_Builder*)
    addTradeTimesWithComDzhyunProtoDzhyunStatic_TradeTime_Builder:
    (ComDzhyunProtoDzhyunStatic_TradeTime_Builder *)value;

@end

FOUNDATION_EXPORT ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunStatic_Static_Builder_getDescriptor();

J2OBJC_EMPTY_STATIC_INIT(ComDzhyunProtoDzhyunStatic_Static_Builder)

J2OBJC_TYPE_LITERAL_HEADER(ComDzhyunProtoDzhyunStatic_Static_Builder)

@protocol ComDzhyunProtoDzhyunStatic_StaticTableOrBuilder < ComGoogleProtobufMessageOrBuilder >

- (int)getRowsCount;
- (id<JavaUtilList>)getRowsList;
- (ComDzhyunProtoDzhyunStatic_Static *)getRowsWithInt:(int)index;

@end

J2OBJC_EMPTY_STATIC_INIT(ComDzhyunProtoDzhyunStatic_StaticTableOrBuilder)

J2OBJC_TYPE_LITERAL_HEADER(ComDzhyunProtoDzhyunStatic_StaticTableOrBuilder)

@interface ComDzhyunProtoDzhyunStatic_StaticTable : ComGoogleProtobufGeneratedMessage<ComDzhyunProtoDzhyunStatic_StaticTableOrBuilder>

+ (ComDzhyunProtoDzhyunStatic_StaticTable *)getDefaultInstance;
- (ComDzhyunProtoDzhyunStatic_StaticTable *)getDefaultInstanceForType;
+ (ComDzhyunProtoDzhyunStatic_StaticTable_Builder *)newBuilder OBJC_METHOD_FAMILY_NONE;
- (ComDzhyunProtoDzhyunStatic_StaticTable_Builder *)newBuilderForType OBJC_METHOD_FAMILY_NONE;
- (ComDzhyunProtoDzhyunStatic_StaticTable_Builder *)toBuilder;
+ (ComDzhyunProtoDzhyunStatic_StaticTable_Builder *)newBuilderWithComDzhyunProtoDzhyunStatic_StaticTable:(ComDzhyunProtoDzhyunStatic_StaticTable *)message OBJC_METHOD_FAMILY_NONE;
+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor;
+ (ComDzhyunProtoDzhyunStatic_StaticTable *)parseFromWithByteArray:(IOSByteArray *)bytes;
+ (ComDzhyunProtoDzhyunStatic_StaticTable *)parseFromWithByteArray:(IOSByteArray *)bytes withComGoogleProtobufExtensionRegistryLite:(ComGoogleProtobufExtensionRegistryLite *)registry;
+ (ComDzhyunProtoDzhyunStatic_StaticTable *)parseFromNSData:(NSData *)data;
+ (ComDzhyunProtoDzhyunStatic_StaticTable *)parseFromNSData:(NSData *)data registry:(ComGoogleProtobufExtensionRegistryLite *)registry;
+ (ComDzhyunProtoDzhyunStatic_StaticTable *)parseFromWithJavaIoInputStream:(JavaIoInputStream *)input;
+ (ComDzhyunProtoDzhyunStatic_StaticTable *)parseFromWithJavaIoInputStream:(JavaIoInputStream *)bytes withComGoogleProtobufExtensionRegistryLite:(ComGoogleProtobufExtensionRegistryLite *)registry;
+ (ComDzhyunProtoDzhyunStatic_StaticTable *)parseDelimitedFromWithJavaIoInputStream:(JavaIoInputStream *)input;
+ (ComDzhyunProtoDzhyunStatic_StaticTable *)parseDelimitedFromWithJavaIoInputStream:(JavaIoInputStream *)bytes withComGoogleProtobufExtensionRegistryLite:(ComGoogleProtobufExtensionRegistryLite *)registry;

#define ComDzhyunProtoDzhyunStatic_StaticTable_ROWS_FIELD_NUMBER 1

@end

FOUNDATION_EXPORT ComDzhyunProtoDzhyunStatic_StaticTable *ComDzhyunProtoDzhyunStatic_StaticTable_getDefaultInstance();
FOUNDATION_EXPORT ComDzhyunProtoDzhyunStatic_StaticTable_Builder *ComDzhyunProtoDzhyunStatic_StaticTable_newBuilder();
FOUNDATION_EXPORT ComDzhyunProtoDzhyunStatic_StaticTable_Builder *ComDzhyunProtoDzhyunStatic_StaticTable_newBuilderWithComDzhyunProtoDzhyunStatic_StaticTable_(ComDzhyunProtoDzhyunStatic_StaticTable *message);
FOUNDATION_EXPORT ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunStatic_StaticTable_getDescriptor();
FOUNDATION_EXPORT ComDzhyunProtoDzhyunStatic_StaticTable *ComDzhyunProtoDzhyunStatic_StaticTable_parseFromWithByteArray_withComGoogleProtobufExtensionRegistryLite_(IOSByteArray *bytes, ComGoogleProtobufExtensionRegistryLite *registry);
CGP_ALWAYS_INLINE inline ComDzhyunProtoDzhyunStatic_StaticTable *ComDzhyunProtoDzhyunStatic_StaticTable_parseFromWithByteArray_(IOSByteArray *bytes) {
  return ComDzhyunProtoDzhyunStatic_StaticTable_parseFromWithByteArray_withComGoogleProtobufExtensionRegistryLite_(bytes, nil);
}
FOUNDATION_EXPORT ComDzhyunProtoDzhyunStatic_StaticTable *ComDzhyunProtoDzhyunStatic_StaticTable_parseFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry);
CGP_ALWAYS_INLINE inline ComDzhyunProtoDzhyunStatic_StaticTable *ComDzhyunProtoDzhyunStatic_StaticTable_parseFromWithJavaIoInputStream_(JavaIoInputStream *input) {
  return ComDzhyunProtoDzhyunStatic_StaticTable_parseFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(input, nil);
}
FOUNDATION_EXPORT ComDzhyunProtoDzhyunStatic_StaticTable *ComDzhyunProtoDzhyunStatic_StaticTable_parseDelimitedFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry);
CGP_ALWAYS_INLINE inline ComDzhyunProtoDzhyunStatic_StaticTable *ComDzhyunProtoDzhyunStatic_StaticTable_parseDelimitedFromWithJavaIoInputStream_(JavaIoInputStream *input) {
  return ComDzhyunProtoDzhyunStatic_StaticTable_parseDelimitedFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(input, nil);
}

J2OBJC_STATIC_INIT(ComDzhyunProtoDzhyunStatic_StaticTable)

J2OBJC_TYPE_LITERAL_HEADER(ComDzhyunProtoDzhyunStatic_StaticTable)

FOUNDATION_EXPORT ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunStatic_StaticTable_descriptor_;

@interface ComDzhyunProtoDzhyunStatic_StaticTable_Builder : ComGoogleProtobufGeneratedMessage_Builder<ComDzhyunProtoDzhyunStatic_StaticTableOrBuilder>

- (ComDzhyunProtoDzhyunStatic_StaticTable *)getDefaultInstanceForType;
- (ComDzhyunProtoDzhyunStatic_StaticTable_Builder *)mergeFromWithComDzhyunProtoDzhyunStatic_StaticTable:(ComDzhyunProtoDzhyunStatic_StaticTable *)message;
- (ComDzhyunProtoDzhyunStatic_StaticTable_Builder *)mergeFromWithComGoogleProtobufMessage:(id<ComGoogleProtobufMessage>)message;
- (ComDzhyunProtoDzhyunStatic_StaticTable *)build;
- (ComDzhyunProtoDzhyunStatic_StaticTable *)buildPartial;
+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor;
- (ComDzhyunProtoDzhyunStatic_StaticTable_Builder*)setRowsWithInt:(int)index
    withComDzhyunProtoDzhyunStatic_Static:(ComDzhyunProtoDzhyunStatic_Static *)value;
- (ComDzhyunProtoDzhyunStatic_StaticTable_Builder*)addRowsWithComDzhyunProtoDzhyunStatic_Static:
    (ComDzhyunProtoDzhyunStatic_Static *)value;
- (ComDzhyunProtoDzhyunStatic_StaticTable_Builder*)addAllRowsWithJavaLangIterable:
    (id<JavaLangIterable>)values;
- (ComDzhyunProtoDzhyunStatic_StaticTable_Builder*)clearRows;
- (ComDzhyunProtoDzhyunStatic_StaticTable_Builder*)
    addRowsWithComDzhyunProtoDzhyunStatic_Static_Builder:
    (ComDzhyunProtoDzhyunStatic_Static_Builder *)value;

@end

FOUNDATION_EXPORT ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunStatic_StaticTable_Builder_getDescriptor();

J2OBJC_EMPTY_STATIC_INIT(ComDzhyunProtoDzhyunStatic_StaticTable_Builder)

J2OBJC_TYPE_LITERAL_HEADER(ComDzhyunProtoDzhyunStatic_StaticTable_Builder)
