// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dzhyun.zhibiaojisuan.proto

#import "J2ObjC_source.h"
#import "com/dzhyun/proto/DzhyunZhibiaojisuan.h"
#import "com/google/protobuf/Descriptors_PackagePrivate.h"
#import "com/google/protobuf/ExtensionRegistry.h"
#import "com/google/protobuf/GeneratedMessage_PackagePrivate.h"
#import "com/google/protobuf/RepeatedField.h"
#import "java/lang/IllegalArgumentException.h"

#pragma GCC diagnostic ignored "-Wprotocol"
#pragma clang diagnostic ignored "-Wprotocol"
#pragma GCC diagnostic ignored "-Wincomplete-implementation"
#pragma clang diagnostic ignored "-Wincomplete-implementation"

@implementation ComDzhyunProtoDzhyunZhibiaojisuan

+ (void)registerAllExtensionsWithComGoogleProtobufExtensionRegistry:(ComGoogleProtobufExtensionRegistry *)extensionRegistry {
  ComDzhyunProtoDzhyunZhibiaojisuan_registerAllExtensionsWithComGoogleProtobufExtensionRegistry_(extensionRegistry);
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan)

void ComDzhyunProtoDzhyunZhibiaojisuan_registerAllExtensionsWithComGoogleProtobufExtensionRegistry_(ComGoogleProtobufExtensionRegistry *extensionRegistry) {
}

J2OBJC_INITIALIZED_DEFN(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu);

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_descriptor_;

@implementation ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu

typedef struct ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_Storage {
  uint32_t hasBits[1];
  NSString *obj_;
  CGPRepeatedField shuJu_;
  CGPRepeatedField shuXing_;
  CGPRepeatedField huiTu_;
} ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_Storage;

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_descriptor_;
}

+ (void)initialize {
  if (self == [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu class]) {
    static CGPFieldData fields[] = {
      {
        .name = "Obj",
        .javaName = "Obj",
        .number = 1,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_STRING,
        .defaultValue.valueId = @"",
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_Storage, obj_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu",
        .optionsData = NULL,
      },
      {
        .name = "ShuJu",
        .javaName = "ShuJu",
        .number = 2,
        .flags = CGPFieldFlagRepeated,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_MESSAGE,
        .defaultValue.valueId = nil,
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_Storage, shuJu_),
        .className = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu",
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu",
        .optionsData = NULL,
      },
      {
        .name = "ShuXing",
        .javaName = "ShuXing",
        .number = 3,
        .flags = CGPFieldFlagRepeated,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_MESSAGE,
        .defaultValue.valueId = nil,
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_Storage, shuXing_),
        .className = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing",
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu",
        .optionsData = NULL,
      },
      {
        .name = "HuiTu",
        .javaName = "HuiTu",
        .number = 4,
        .flags = CGPFieldFlagRepeated,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_MESSAGE,
        .defaultValue.valueId = nil,
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_Storage, huiTu_),
        .className = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu",
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu",
        .optionsData = NULL,
      },
    };
    CGPInitDescriptor(&ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_descriptor_, self, [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_Builder class], 0, sizeof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_Storage), 4, fields);
    J2OBJC_SET_INITIALIZED(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu)
  }
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu)

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_getDefaultInstance() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu *)[CGPNewMessage(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_descriptor_) autorelease];
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_Builder *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_newBuilder() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_Builder *)[CGPNewBuilder(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_descriptor_) autorelease];
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_Builder *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_newBuilderWithComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu *message) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_Builder *)CGPBuilderFromPrototype(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_descriptor_, message);
}

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_getDescriptor() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_initialize();
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_descriptor_;
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_parseFromWithByteArray_withComGoogleProtobufExtensionRegistryLite_(IOSByteArray *bytes, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu *)CGPParseFromByteArray(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_descriptor_, bytes, registry);
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_parseFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu *)CGPParseFromInputStream(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_descriptor_, input, registry);
}
ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_parseDelimitedFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu *)CGPParseDelimitedFromInputStream(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_descriptor_, input, registry);
}

J2OBJC_INITIALIZED_DEFN(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu);

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_descriptor_;

@implementation ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu

typedef struct ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_Storage {
  uint32_t hasBits[1];
  long long int shiJian_;
  CGPRepeatedField jieGuo_;
} ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_Storage;

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_descriptor_;
}

+ (void)initialize {
  if (self == [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu class]) {
    static CGPFieldData fields[] = {
      {
        .name = "ShiJian",
        .javaName = "ShiJian",
        .number = 1,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_Storage, shiJian_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu",
        .optionsData = NULL,
      },
      {
        .name = "JieGuo",
        .javaName = "JieGuo",
        .number = 2,
        .flags = CGPFieldFlagRepeated,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueId = nil,
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_Storage, jieGuo_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu",
        .optionsData = NULL,
      },
    };
    CGPInitDescriptor(&ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_descriptor_, self, [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_Builder class], 0, sizeof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_Storage), 2, fields);
    J2OBJC_SET_INITIALIZED(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu)
  }
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu)

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_getDefaultInstance() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu *)[CGPNewMessage(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_descriptor_) autorelease];
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_Builder *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_newBuilder() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_Builder *)[CGPNewBuilder(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_descriptor_) autorelease];
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_Builder *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_newBuilderWithComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu *message) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_Builder *)CGPBuilderFromPrototype(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_descriptor_, message);
}

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_getDescriptor() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_initialize();
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_descriptor_;
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_parseFromWithByteArray_withComGoogleProtobufExtensionRegistryLite_(IOSByteArray *bytes, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu *)CGPParseFromByteArray(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_descriptor_, bytes, registry);
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_parseFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu *)CGPParseFromInputStream(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_descriptor_, input, registry);
}
ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_parseDelimitedFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu *)CGPParseDelimitedFromInputStream(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_descriptor_, input, registry);
}

@implementation ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_Builder

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu getDescriptor];
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_Builder)
J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJuOrBuilder)

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_Builder_getDescriptor() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_initialize();
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuJu_descriptor_;
}

J2OBJC_INITIALIZED_DEFN(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing);

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_descriptor_;

@implementation ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing

typedef struct ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Storage {
  uint32_t hasBits[1];
  NSString *mingCheng_;
  long long int yanSe_;
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum *leiXing_;
  long long int kuanDu_;
  long long int jingDu_;
  long long int duiQi_;
  long long int shuXing_;
  long long int yiDong_;
  long long int cengCi_;
  long long int bianLiangWeiZhi_;
  long long int kuoZhanShuXing_;
  long long int youXiaoWeiZhi_;
} ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Storage;

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_descriptor_;
}

+ (void)initialize {
  if (self == [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing class]) {
    static CGPFieldData fields[] = {
      {
        .name = "MingCheng",
        .javaName = "MingCheng",
        .number = 1,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_STRING,
        .defaultValue.valueId = @"",
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Storage, mingCheng_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing",
        .optionsData = NULL,
      },
      {
        .name = "YanSe",
        .javaName = "YanSe",
        .number = 2,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 1,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Storage, yanSe_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing",
        .optionsData = NULL,
      },
      {
        .name = "LeiXing",
        .javaName = "LeiXing",
        .number = 3,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_ENUM,
        .defaultValue.valueInt = ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXing_TYPE_TEMP_EXPRESION,
        .hasBitIndex = 2,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Storage, leiXing_),
        .className = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum",
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing",
        .optionsData = NULL,
      },
      {
        .name = "KuanDu",
        .javaName = "KuanDu",
        .number = 4,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 3,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Storage, kuanDu_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing",
        .optionsData = NULL,
      },
      {
        .name = "JingDu",
        .javaName = "JingDu",
        .number = 5,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 4,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Storage, jingDu_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing",
        .optionsData = NULL,
      },
      {
        .name = "DuiQi",
        .javaName = "DuiQi",
        .number = 6,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 5,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Storage, duiQi_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing",
        .optionsData = NULL,
      },
      {
        .name = "ShuXing",
        .javaName = "ShuXing",
        .number = 7,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 6,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Storage, shuXing_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing",
        .optionsData = NULL,
      },
      {
        .name = "YiDong",
        .javaName = "YiDong",
        .number = 8,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 7,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Storage, yiDong_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing",
        .optionsData = NULL,
      },
      {
        .name = "CengCi",
        .javaName = "CengCi",
        .number = 9,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 8,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Storage, cengCi_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing",
        .optionsData = NULL,
      },
      {
        .name = "BianLiangWeiZhi",
        .javaName = "BianLiangWeiZhi",
        .number = 10,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 9,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Storage, bianLiangWeiZhi_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing",
        .optionsData = NULL,
      },
      {
        .name = "KuoZhanShuXing",
        .javaName = "KuoZhanShuXing",
        .number = 11,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 10,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Storage, kuoZhanShuXing_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing",
        .optionsData = NULL,
      },
      {
        .name = "YouXiaoWeiZhi",
        .javaName = "YouXiaoWeiZhi",
        .number = 12,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 11,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Storage, youXiaoWeiZhi_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing",
        .optionsData = NULL,
      },
    };
    CGPInitDescriptor(&ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_descriptor_, self, [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Builder class], 0, sizeof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Storage), 12, fields);
    J2OBJC_SET_INITIALIZED(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing)
  }
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing)

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_getDefaultInstance() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing *)[CGPNewMessage(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_descriptor_) autorelease];
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Builder *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_newBuilder() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Builder *)[CGPNewBuilder(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_descriptor_) autorelease];
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Builder *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_newBuilderWithComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing *message) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Builder *)CGPBuilderFromPrototype(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_descriptor_, message);
}

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_getDescriptor() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_initialize();
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_descriptor_;
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_parseFromWithByteArray_withComGoogleProtobufExtensionRegistryLite_(IOSByteArray *bytes, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing *)CGPParseFromByteArray(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_descriptor_, bytes, registry);
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_parseFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing *)CGPParseFromInputStream(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_descriptor_, input, registry);
}
ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_parseDelimitedFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing *)CGPParseDelimitedFromInputStream(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_descriptor_, input, registry);
}

J2OBJC_INITIALIZED_DEFN(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum)

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_values_[18];

static ComGoogleProtobufDescriptors_EnumDescriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_descriptor = nil;

@implementation ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum

- (id)initWithName:(NSString *)name withIndex:(jint)index withValue:(jint)value {
  if (self = [super initWithNSString:name withInt:index]) {
    value_ = value;
  }
  return self;
}

+ (void)initialize {
  if (self == [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum class]) {
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_TYPE_TEMP_EXPRESION = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum alloc] initWithName:@"TYPE_TEMP_EXPRESION" withIndex:0 withValue:0];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_TYPE_CURV_LINE = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum alloc] initWithName:@"TYPE_CURV_LINE" withIndex:1 withValue:1];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_TYPE_STICK_LINE = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum alloc] initWithName:@"TYPE_STICK_LINE" withIndex:2 withValue:2];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_TYPE_COLORSTICK_LINE = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum alloc] initWithName:@"TYPE_COLORSTICK_LINE" withIndex:3 withValue:3];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_TYPE_VOLSTICK_LINE = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum alloc] initWithName:@"TYPE_VOLSTICK_LINE" withIndex:4 withValue:4];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_TYPE_LINESTICK_LINE = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum alloc] initWithName:@"TYPE_LINESTICK_LINE" withIndex:5 withValue:5];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_TYPE_CROSS_DOT = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum alloc] initWithName:@"TYPE_CROSS_DOT" withIndex:6 withValue:6];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_TYPE_CIRCLE_DOT = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum alloc] initWithName:@"TYPE_CIRCLE_DOT" withIndex:7 withValue:7];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_TYPE_POINT_DOT = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum alloc] initWithName:@"TYPE_POINT_DOT" withIndex:8 withValue:8];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_TYPE_STICK3D_LINE = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum alloc] initWithName:@"TYPE_STICK3D_LINE" withIndex:9 withValue:9];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_TYPE_COLOR3D_LINE = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum alloc] initWithName:@"TYPE_COLOR3D_LINE" withIndex:10 withValue:10];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_TYPE_DOT_DOT = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum alloc] initWithName:@"TYPE_DOT_DOT" withIndex:11 withValue:11];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_TYPE_DASH_DOT = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum alloc] initWithName:@"TYPE_DASH_DOT" withIndex:12 withValue:12];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_TYPE_PERCENT_BAR = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum alloc] initWithName:@"TYPE_PERCENT_BAR" withIndex:13 withValue:13];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_TYPE_ENTER_LONG = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum alloc] initWithName:@"TYPE_ENTER_LONG" withIndex:14 withValue:100];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_TYPE_EXIT_LONG = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum alloc] initWithName:@"TYPE_EXIT_LONG" withIndex:15 withValue:101];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_TYPE_ENTER_SHORT = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum alloc] initWithName:@"TYPE_ENTER_SHORT" withIndex:16 withValue:102];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_TYPE_EXIT_SHORT = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum alloc] initWithName:@"TYPE_EXIT_SHORT" withIndex:17 withValue:103];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_descriptor = CGPNewEnumDescriptor(self, 18, ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_values_);
    J2OBJC_SET_INITIALIZED(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum)
  }
}

+ (IOSObjectArray *)values {
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_values();}

+ (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum *)valueOfWithNSString:(NSString *)name {
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_valueOfWithNSString_(name);
}

+ (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum *)valueOfWithInt:(jint)value {
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_valueOfWithInt_(value);
}

- (jint)getNumber {
  return value_;
}

+ (ComGoogleProtobufDescriptors_EnumDescriptor *)getDescriptor {
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_descriptor;
}

- (ComGoogleProtobufDescriptors_EnumValueDescriptor *)getValueDescriptor {
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_descriptor->values_->buffer_[[self ordinal]];
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum)

IOSObjectArray *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_values() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_initialize();  return [IOSObjectArray arrayWithObjects:ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_values_ count:18 type:ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_class_()];
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_valueOfWithNSString_(NSString *name) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_initialize();  for (jint i = 0; i < 18; i++) {
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum *e = ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc] initWithNSString:name] autorelease];
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_valueOfWithInt_(jint value) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_initialize();  for (jint i = 0; i < 18; i++) {
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum *e = ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum_values_[i];
    if (value == [e getNumber]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc]
      initWithNSString:[NSString stringWithFormat:@"%d", value]] autorelease];
}


@implementation ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Builder

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing getDescriptor];
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Builder)
J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXingOrBuilder)

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_Builder_getDescriptor() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_initialize();
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_descriptor_;
}

J2OBJC_INITIALIZED_DEFN(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu);

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_descriptor_;

@implementation ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu

typedef struct ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_Storage {
  uint32_t hasBits[1];
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum *leiXing_;
  long long int kuanDu_;
  long long int shuXing_;
  long long int shangCiJiSuan_;
  long long int yanSe_;
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum *shuChuLeiXing_;
  long long int shuChuShuXing_;
  long long int shuChuKuoZhanShuXing_;
  CGPRepeatedField wenBen_;
  CGPRepeatedField shuJu_;
} ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_Storage;

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_descriptor_;
}

+ (void)initialize {
  if (self == [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu class]) {
    static CGPFieldData fields[] = {
      {
        .name = "LeiXing",
        .javaName = "LeiXing",
        .number = 1,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_ENUM,
        .defaultValue.valueInt = ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXing_TYPE_NOLINE,
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_Storage, leiXing_),
        .className = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum",
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu",
        .optionsData = NULL,
      },
      {
        .name = "KuanDu",
        .javaName = "KuanDu",
        .number = 2,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 1,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_Storage, kuanDu_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu",
        .optionsData = NULL,
      },
      {
        .name = "ShuXing",
        .javaName = "ShuXing",
        .number = 3,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 2,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_Storage, shuXing_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu",
        .optionsData = NULL,
      },
      {
        .name = "ShangCiJiSuan",
        .javaName = "ShangCiJiSuan",
        .number = 4,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 3,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_Storage, shangCiJiSuan_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu",
        .optionsData = NULL,
      },
      {
        .name = "YanSe",
        .javaName = "YanSe",
        .number = 5,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 4,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_Storage, yanSe_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu",
        .optionsData = NULL,
      },
      {
        .name = "ShuChuLeiXing",
        .javaName = "ShuChuLeiXing",
        .number = 6,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_ENUM,
        .defaultValue.valueInt = ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXing_TYPE_TEMP_EXPRESION,
        .hasBitIndex = 5,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_Storage, shuChuLeiXing_),
        .className = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing_SXLeiXingEnum",
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu",
        .optionsData = NULL,
      },
      {
        .name = "ShuChuShuXing",
        .javaName = "ShuChuShuXing",
        .number = 7,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 6,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_Storage, shuChuShuXing_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu",
        .optionsData = NULL,
      },
      {
        .name = "ShuChuKuoZhanShuXing",
        .javaName = "ShuChuKuoZhanShuXing",
        .number = 8,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 7,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_Storage, shuChuKuoZhanShuXing_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu",
        .optionsData = NULL,
      },
      {
        .name = "WenBen",
        .javaName = "WenBen",
        .number = 9,
        .flags = CGPFieldFlagRepeated,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_STRING,
        .defaultValue.valueId = nil,
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_Storage, wenBen_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu",
        .optionsData = NULL,
      },
      {
        .name = "ShuJu",
        .javaName = "ShuJu",
        .number = 10,
        .flags = CGPFieldFlagRepeated,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_MESSAGE,
        .defaultValue.valueId = nil,
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_Storage, shuJu_),
        .className = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu",
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu",
        .optionsData = NULL,
      },
    };
    CGPInitDescriptor(&ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_descriptor_, self, [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_Builder class], 0, sizeof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_Storage), 10, fields);
    J2OBJC_SET_INITIALIZED(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu)
  }
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu)

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_getDefaultInstance() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu *)[CGPNewMessage(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_descriptor_) autorelease];
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_Builder *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_newBuilder() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_Builder *)[CGPNewBuilder(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_descriptor_) autorelease];
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_Builder *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_newBuilderWithComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu *message) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_Builder *)CGPBuilderFromPrototype(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_descriptor_, message);
}

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_getDescriptor() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_initialize();
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_descriptor_;
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_parseFromWithByteArray_withComGoogleProtobufExtensionRegistryLite_(IOSByteArray *bytes, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu *)CGPParseFromByteArray(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_descriptor_, bytes, registry);
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_parseFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu *)CGPParseFromInputStream(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_descriptor_, input, registry);
}
ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_parseDelimitedFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu *)CGPParseDelimitedFromInputStream(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_descriptor_, input, registry);
}

J2OBJC_INITIALIZED_DEFN(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum)

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_values_[18];

static ComGoogleProtobufDescriptors_EnumDescriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_descriptor = nil;

@implementation ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum

- (id)initWithName:(NSString *)name withIndex:(jint)index withValue:(jint)value {
  if (self = [super initWithNSString:name withInt:index]) {
    value_ = value;
  }
  return self;
}

+ (void)initialize {
  if (self == [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum class]) {
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_TYPE_NOLINE = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum alloc] initWithName:@"TYPE_NOLINE" withIndex:0 withValue:0];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_TYPE_POLYLINE = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum alloc] initWithName:@"TYPE_POLYLINE" withIndex:1 withValue:1];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_TYPE_LINE = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum alloc] initWithName:@"TYPE_LINE" withIndex:2 withValue:2];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_TYPE_STICKLINE = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum alloc] initWithName:@"TYPE_STICKLINE" withIndex:3 withValue:3];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_TYPE_TEXT = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum alloc] initWithName:@"TYPE_TEXT" withIndex:4 withValue:4];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_TYPE_ICON = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum alloc] initWithName:@"TYPE_ICON" withIndex:5 withValue:5];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_TYPE_TIP_TEXT = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum alloc] initWithName:@"TYPE_TIP_TEXT" withIndex:6 withValue:6];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_TYPE_BACK_GRD = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum alloc] initWithName:@"TYPE_BACK_GRD" withIndex:7 withValue:7];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_TYPE_BACK_GRDLAST = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum alloc] initWithName:@"TYPE_BACK_GRDLAST" withIndex:8 withValue:8];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_TYPE_DRAWBMP = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum alloc] initWithName:@"TYPE_DRAWBMP" withIndex:9 withValue:9];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_TYPE_VERTLINE = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum alloc] initWithName:@"TYPE_VERTLINE" withIndex:10 withValue:10];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_TYPE_TEXTABS = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum alloc] initWithName:@"TYPE_TEXTABS" withIndex:11 withValue:11];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_TYPE_TEXTREL = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum alloc] initWithName:@"TYPE_TEXTREL" withIndex:12 withValue:12];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_TYPE_RECTABS = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum alloc] initWithName:@"TYPE_RECTABS" withIndex:13 withValue:13];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_TYPE_RECTREL = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum alloc] initWithName:@"TYPE_RECTREL" withIndex:14 withValue:14];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_TYPE_FLAGTEXT = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum alloc] initWithName:@"TYPE_FLAGTEXT" withIndex:15 withValue:15];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_TYPE_MOVETEXT = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum alloc] initWithName:@"TYPE_MOVETEXT" withIndex:16 withValue:16];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_TYPE_HORILINE = [[ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum alloc] initWithName:@"TYPE_HORILINE" withIndex:17 withValue:17];
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_descriptor = CGPNewEnumDescriptor(self, 18, ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_values_);
    J2OBJC_SET_INITIALIZED(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum)
  }
}

+ (IOSObjectArray *)values {
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_values();}

+ (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum *)valueOfWithNSString:(NSString *)name {
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_valueOfWithNSString_(name);
}

+ (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum *)valueOfWithInt:(jint)value {
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_valueOfWithInt_(value);
}

- (jint)getNumber {
  return value_;
}

+ (ComGoogleProtobufDescriptors_EnumDescriptor *)getDescriptor {
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_descriptor;
}

- (ComGoogleProtobufDescriptors_EnumValueDescriptor *)getValueDescriptor {
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_descriptor->values_->buffer_[[self ordinal]];
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum)

IOSObjectArray *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_values() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_initialize();  return [IOSObjectArray arrayWithObjects:ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_values_ count:18 type:ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_class_()];
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_valueOfWithNSString_(NSString *name) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_initialize();  for (jint i = 0; i < 18; i++) {
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum *e = ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc] initWithNSString:name] autorelease];
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_valueOfWithInt_(jint value) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_initialize();  for (jint i = 0; i < 18; i++) {
    ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum *e = ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTLeiXingEnum_values_[i];
    if (value == [e getNumber]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc]
      initWithNSString:[NSString stringWithFormat:@"%d", value]] autorelease];
}


J2OBJC_INITIALIZED_DEFN(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu);

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_descriptor_;

@implementation ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu

typedef struct ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_Storage {
  uint32_t hasBits[1];
  long long int weiZhi_;
  long long int jiaGe_;
  long long int canShu_;
} ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_Storage;

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_descriptor_;
}

+ (void)initialize {
  if (self == [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu class]) {
    static CGPFieldData fields[] = {
      {
        .name = "WeiZhi",
        .javaName = "WeiZhi",
        .number = 1,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_Storage, weiZhi_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu",
        .optionsData = NULL,
      },
      {
        .name = "JiaGe",
        .javaName = "JiaGe",
        .number = 2,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 1,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_Storage, jiaGe_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu",
        .optionsData = NULL,
      },
      {
        .name = "CanShu",
        .javaName = "CanShu",
        .number = 3,
        .flags = CGPFieldFlagRequired,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_INT64,
        .defaultValue.valueLong = 0LL,
        .hasBitIndex = 2,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_Storage, canShu_),
        .className = NULL,
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu",
        .optionsData = NULL,
      },
    };
    CGPInitDescriptor(&ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_descriptor_, self, [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_Builder class], 0, sizeof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_Storage), 3, fields);
    J2OBJC_SET_INITIALIZED(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu)
  }
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu)

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_getDefaultInstance() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu *)[CGPNewMessage(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_descriptor_) autorelease];
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_Builder *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_newBuilder() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_Builder *)[CGPNewBuilder(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_descriptor_) autorelease];
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_Builder *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_newBuilderWithComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu *message) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_Builder *)CGPBuilderFromPrototype(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_descriptor_, message);
}

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_getDescriptor() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_initialize();
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_descriptor_;
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_parseFromWithByteArray_withComGoogleProtobufExtensionRegistryLite_(IOSByteArray *bytes, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu *)CGPParseFromByteArray(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_descriptor_, bytes, registry);
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_parseFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu *)CGPParseFromInputStream(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_descriptor_, input, registry);
}
ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_parseDelimitedFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu *)CGPParseDelimitedFromInputStream(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_descriptor_, input, registry);
}

@implementation ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_Builder

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu getDescriptor];
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_Builder)
J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJuOrBuilder)

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_Builder_getDescriptor() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_initialize();
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_HTShuJu_descriptor_;
}

@implementation ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_Builder

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu getDescriptor];
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_Builder)
J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTuOrBuilder)

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_Builder_getDescriptor() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_initialize();
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu_descriptor_;
}

@implementation ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_Builder

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu getDescriptor];
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_Builder)
J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChuOrBuilder)

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_Builder_getDescriptor() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_initialize();
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_descriptor_;
}

J2OBJC_INITIALIZED_DEFN(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu);

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_descriptor_;

@implementation ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu

typedef struct ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_Storage {
  uint32_t hasBits[0];
  CGPRepeatedField shuChu_;
} ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_Storage;

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_descriptor_;
}

+ (void)initialize {
  if (self == [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu class]) {
    static CGPFieldData fields[] = {
      {
        .name = "ShuChu",
        .javaName = "ShuChu",
        .number = 1,
        .flags = CGPFieldFlagRepeated,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_MESSAGE,
        .defaultValue.valueId = nil,
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_Storage, shuChu_),
        .className = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBShuXing",
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu",
        .optionsData = NULL,
      },
    };
    CGPInitDescriptor(&ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_descriptor_, self, [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_Builder class], 0, sizeof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_Storage), 1, fields);
    J2OBJC_SET_INITIALIZED(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu)
  }
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu)

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_getDefaultInstance() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu *)[CGPNewMessage(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_descriptor_) autorelease];
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_Builder *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_newBuilder() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_Builder *)[CGPNewBuilder(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_descriptor_) autorelease];
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_Builder *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_newBuilderWithComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu *message) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_Builder *)CGPBuilderFromPrototype(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_descriptor_, message);
}

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_getDescriptor() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_initialize();
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_descriptor_;
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_parseFromWithByteArray_withComGoogleProtobufExtensionRegistryLite_(IOSByteArray *bytes, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu *)CGPParseFromByteArray(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_descriptor_, bytes, registry);
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_parseFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu *)CGPParseFromInputStream(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_descriptor_, input, registry);
}
ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_parseDelimitedFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu *)CGPParseDelimitedFromInputStream(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_descriptor_, input, registry);
}

@implementation ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_Builder

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu getDescriptor];
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_Builder)
J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChuOrBuilder)

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_Builder_getDescriptor() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_initialize();
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuXingShuChu_descriptor_;
}

J2OBJC_INITIALIZED_DEFN(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu);

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_descriptor_;

@implementation ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu

typedef struct ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_Storage {
  uint32_t hasBits[0];
  CGPRepeatedField shuChu_;
} ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_Storage;

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_descriptor_;
}

+ (void)initialize {
  if (self == [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu class]) {
    static CGPFieldData fields[] = {
      {
        .name = "ShuChu",
        .javaName = "ShuChu",
        .number = 1,
        .flags = CGPFieldFlagRepeated,
        .type = ComGoogleProtobufDescriptors_FieldDescriptor_Type_MESSAGE,
        .defaultValue.valueId = nil,
        .hasBitIndex = 0,
        .offset = offsetof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_Storage, shuChu_),
        .className = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoShuChu_ZBHuiTu",
        .containingType = "ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu",
        .optionsData = NULL,
      },
    };
    CGPInitDescriptor(&ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_descriptor_, self, [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_Builder class], 0, sizeof(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_Storage), 1, fields);
    J2OBJC_SET_INITIALIZED(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu)
  }
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu)

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_getDefaultInstance() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu *)[CGPNewMessage(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_descriptor_) autorelease];
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_Builder *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_newBuilder() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_Builder *)[CGPNewBuilder(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_descriptor_) autorelease];
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_Builder *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_newBuilderWithComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu *message) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_Builder *)CGPBuilderFromPrototype(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_descriptor_, message);
}

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_getDescriptor() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_initialize();
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_descriptor_;
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_parseFromWithByteArray_withComGoogleProtobufExtensionRegistryLite_(IOSByteArray *bytes, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu *)CGPParseFromByteArray(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_descriptor_, bytes, registry);
}

ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_parseFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu *)CGPParseFromInputStream(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_descriptor_, input, registry);
}
ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_parseDelimitedFromWithJavaIoInputStream_withComGoogleProtobufExtensionRegistryLite_(JavaIoInputStream *input, ComGoogleProtobufExtensionRegistryLite *registry) {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_initialize();
  return (ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu *)CGPParseDelimitedFromInputStream(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_descriptor_, input, registry);
}

@implementation ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_Builder

+ (ComGoogleProtobufDescriptors_Descriptor *)getDescriptor {
  return [ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu getDescriptor];
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_Builder)
J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChuOrBuilder)

ComGoogleProtobufDescriptors_Descriptor *ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_Builder_getDescriptor() {
  ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_initialize();
  return ComDzhyunProtoDzhyunZhibiaojisuan_ZhiBiaoHuiTuShuChu_descriptor_;
}
